/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#ifndef SWIG_TEMPLATE_DISAMBIGUATOR
#  if defined(__SUNPRO_CC) 
#    define SWIG_TEMPLATE_DISAMBIGUATOR template
#  else
#    define SWIG_TEMPLATE_DISAMBIGUATOR 
#  endif
#endif

/* ruby.swg */
/* Implementation : RUBY */
#define SWIGRUBY 1

#include "ruby.h"

/* Flags for pointer conversion */
#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

#define NUM2USHRT(n) (\
    (0 <= NUM2UINT(n) && NUM2UINT(n) <= USHRT_MAX)\
    ? (unsigned short) NUM2UINT(n) \
    : (rb_raise(rb_eArgError, "integer %d out of range of `unsigned short'",\
               NUM2UINT(n)), (short)0)\
)

#define NUM2SHRT(n) (\
    (SHRT_MIN <= NUM2INT(n) && NUM2INT(n) <= SHRT_MAX)\
    ? (short)NUM2INT(n)\
    : (rb_raise(rb_eArgError, "integer %d out of range of `short'",\
               NUM2INT(n)), (short)0)\
)

/* Ruby 1.7 defines NUM2LL(), LL2NUM() and ULL2NUM() macros */
#ifndef NUM2LL
#define NUM2LL(x) NUM2LONG((x))
#endif
#ifndef LL2NUM
#define LL2NUM(x) INT2NUM((long) (x))
#endif
#ifndef ULL2NUM
#define ULL2NUM(x) UINT2NUM((unsigned long) (x))
#endif

/* Ruby 1.7 doesn't (yet) define NUM2ULL() */
#ifndef NUM2ULL
#ifdef HAVE_LONG_LONG
#define NUM2ULL(x) rb_num2ull((x))
#else
#define NUM2ULL(x) NUM2ULONG(x)
#endif
#endif

/*
 * Need to be very careful about how these macros are defined, especially
 * when compiling C++ code or C code with an ANSI C compiler.
 *
 * VALUEFUNC(f) is a macro used to typecast a C function that implements
 * a Ruby method so that it can be passed as an argument to API functions
 * like rb_define_method() and rb_define_singleton_method().
 *
 * VOIDFUNC(f) is a macro used to typecast a C function that implements
 * either the "mark" or "free" stuff for a Ruby Data object, so that it
 * can be passed as an argument to API functions like Data_Wrap_Struct()
 * and Data_Make_Struct().
 */
 
#ifdef __cplusplus
#  ifndef RUBY_METHOD_FUNC /* These definitions should work for Ruby 1.4.6 */
#    define PROTECTFUNC(f) ((VALUE (*)()) f)
#    define VALUEFUNC(f) ((VALUE (*)()) f)
#    define VOIDFUNC(f)  ((void (*)()) f)
#  else
#    ifndef ANYARGS /* These definitions should work for Ruby 1.6 */
#      define PROTECTFUNC(f) ((VALUE (*)()) f)
#      define VALUEFUNC(f) ((VALUE (*)()) f)
#      define VOIDFUNC(f)  ((RUBY_DATA_FUNC) f)
#    else /* These definitions should work for Ruby 1.7+ */
#      define PROTECTFUNC(f) ((VALUE (*)(VALUE)) f)
#      define VALUEFUNC(f) ((VALUE (*)(ANYARGS)) f)
#      define VOIDFUNC(f)  ((RUBY_DATA_FUNC) f)
#    endif
#  endif
#else
#  define VALUEFUNC(f) (f)
#  define VOIDFUNC(f) (f)
#endif

typedef struct {
  VALUE klass;
  VALUE mImpl;
  void  (*mark)(void *);
  void  (*destroy)(void *);
} swig_class;

/* Don't use for expressions have side effect */
#ifndef RB_STRING_VALUE
#define RB_STRING_VALUE(s) (TYPE(s) == T_STRING ? (s) : (*(volatile VALUE *)&(s) = rb_str_to_str(s)))
#endif
#ifndef StringValue
#define StringValue(s) RB_STRING_VALUE(s)
#endif
#ifndef StringValuePtr
#define StringValuePtr(s) RSTRING(RB_STRING_VALUE(s))->ptr
#endif
#ifndef StringValueLen
#define StringValueLen(s) RSTRING(RB_STRING_VALUE(s))->len
#endif
#ifndef SafeStringValue
#define SafeStringValue(v) do {\
    StringValue(v);\
    rb_check_safe_str(v);\
} while (0)
#endif

#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
#define rb_define_alloc_func(klass, func) rb_define_singleton_method((klass), "new", VALUEFUNC((func)), -1)
#define rb_undef_alloc_func(klass) rb_undef_method(CLASS_OF((klass)), "new")
#endif

/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) { rb_raise(rb_eRuntimeError, (char *) msg ); } else


/***********************************************************************
 * swigrun.swg
 *
 *     This file contains generic CAPI SWIG runtime support for pointer
 *     type checking.
 *
 ************************************************************************/

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "1"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
#define SWIG_QUOTE_STRING(x) #x
#define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
#define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
#define SWIG_TYPE_TABLE_NAME
#endif

#include <string.h>

#ifndef SWIGINLINE
#if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#  define SWIGINLINE inline
#else
#  define SWIGINLINE
#endif
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the swig runtime code.
  In 99.9% of the cases, swig just needs to declare them as 'static'.
  
  But only do this if is strictly necessary, ie, if you have problems
  with your compiler or so.
*/
#ifndef SWIGRUNTIME
#define SWIGRUNTIME static
#endif
#ifndef SWIGRUNTIMEINLINE
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

/* 
  Compare two type names skipping the space characters, therefore
  "char*" == "char *" and "Class<int>" == "Class<int >", etc.

  Return 0 when the two name types are equivalent, as in
  strncmp, but skipping ' '.
*/
SWIGRUNTIME int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return *f1 - *f2;
  }
  return (l1 - f1) - (l2 - f2);
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
*/
SWIGRUNTIME int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  int equiv = 0;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (!equiv && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te) == 0;
    if (*ne) ++ne;
  }
  return equiv;
}

/*
  Register a type mapping with the type-checking
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeRegisterTL(swig_type_info **tl, swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = *tl;
  while (tc) {
    /* check simple type equivalence */
    int typeequiv = (strcmp(tc->name, ti->name) == 0);   
    /* check full type equivalence, resolving typedefs */
    if (!typeequiv) {
      /* only if tc is not a typedef (no '|' on it) */
      if (tc->str && ti->str && !strstr(tc->str,"|")) {
	typeequiv = SWIG_TypeEquiv(ti->str,tc->str);
      }
    }
    if (typeequiv) {
      /* Already exists in the table.  Just add additional types to the list */
      if (ti->clientdata) tc->clientdata = ti->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = *tl;
  *tl = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;

  return ret;
}

/*
  Check the typename
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeCheck(const char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/*
  Cast a pointer up an inheritance hierarchy
*/
SWIGRUNTIMEINLINE void *
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr);
}

/* 
   Dynamic pointer casting. Down an inheritance hierarchy
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/*
  Return the name associated with this type
*/
SWIGRUNTIMEINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/*
  Return the pretty name associated with this type,
  that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/*
  Search for a swig_type_info structure
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeQueryTL(swig_type_info *tl, const char *name) {
  swig_type_info *ty = tl;
  while (ty) {
    if (ty->str && (SWIG_TypeEquiv(ty->str,name))) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* 
   Set the clientdata field for a type
*/
SWIGRUNTIME void
SWIG_TypeClientDataTL(swig_type_info *tl, swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = tl;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientDataTL(tl,tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* 
   Pack binary data into a string
*/
SWIGRUNTIME char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static char hex[17] = "0123456789abcdef";
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  register unsigned char uu;
  for (; u != eu; ++u) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* 
   Unpack binary data from a string
*/
SWIGRUNTIME const char *
SWIG_UnpackData(const char *c, void *ptr, size_t sz) {
  register unsigned char *u = (unsigned char *) ptr;
  register const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    register int d = *(c++);
    register unsigned char uu = 0;
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    else 
      return (char *) 0;
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    else 
      return (char *) 0;
    *u = uu;
  }
  return c;
}

/*
  This function will propagate the clientdata field of type to any new
  swig_type_info structures that have been added into the list of
  equivalent types.  It is like calling SWIG_TypeClientData(type,
  clientdata) a second time.
*/
SWIGRUNTIME void
SWIG_PropagateClientDataTL(swig_type_info *tl, swig_type_info *type) {
  swig_type_info *equiv = type->next;
  swig_type_info *tc;
  if (!type->clientdata) return;
  while (equiv) {
    if (!equiv->converter) {
      tc = tl;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0) && !tc->clientdata)
          SWIG_TypeClientDataTL(tl,tc, type->clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* 
   Pack 'void *' into a string buffer.
*/
SWIGRUNTIME char *
SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz) {
  char *r = buff;
  if ((2*sizeof(void *) + 2) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,&ptr,sizeof(void *));
  if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
  strcpy(r,name);
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      *ptr = (void *) 0;
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sizeof(void *));
}

SWIGRUNTIME char *
SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz) {
  char *r = buff;
  size_t lname = (name ? strlen(name) : 0);
  if ((2*sz + 2 + lname) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  if (lname) {
    strncpy(r,name,lname+1);
  } else {
    *r = 0;
  }
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      memset(ptr,0,sz);
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sz);
}

#ifdef __cplusplus
}
#endif

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/


#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if !defined(STATIC_LINKED)
#    define SWIGEXPORT(a) __declspec(dllexport) a
#  else
#    define SWIGEXPORT(a) a
#  endif
#else
#  define SWIGEXPORT(a) a
#endif

#ifdef __cplusplus
extern "C" {
#endif


/*************************************************************************/


/* The static type info list */

static swig_type_info *swig_type_list = 0;
static swig_type_info **swig_type_list_handle = &swig_type_list;
  

/* Register a type mapping with the type-checking */
static swig_type_info *
SWIG_TypeRegister(swig_type_info *ti) {
  return SWIG_TypeRegisterTL(swig_type_list_handle, ti);
}

/* Search for a swig_type_info structure */
static swig_type_info *
SWIG_TypeQuery(const char *name) {
  return SWIG_TypeQueryTL(*swig_type_list_handle, name);
}

/* Set the clientdata field for a type */
static void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  SWIG_TypeClientDataTL(*swig_type_list_handle, ti, clientdata);
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
static void
SWIG_PropagateClientData(swig_type_info *type) {
  SWIG_PropagateClientDataTL(*swig_type_list_handle, type);
}

#ifdef __cplusplus
}
#endif

/* Common SWIG API */
#define SWIG_ConvertPtr(obj, pp, type, flags) \
  SWIG_Ruby_ConvertPtr(obj, pp, type, flags)
#define SWIG_NewPointerObj(p, type, flags) \
  SWIG_Ruby_NewPointerObj(p, type, flags)
#define SWIG_MustGetPtr(p, type, argnum, flags) \
  SWIG_Ruby_MustGetPtr(p, type, argnum, flags)

/* Ruby-specific SWIG API */

#define SWIG_InitRuntime() \
  SWIG_Ruby_InitRuntime()
#define SWIG_define_class(ty) \
  SWIG_Ruby_define_class(ty)
#define SWIG_NewClassInstance(value, ty) \
  SWIG_Ruby_NewClassInstance(value, ty)
#define SWIG_MangleStr(value) \
  SWIG_Ruby_MangleStr(value)
#define SWIG_CheckConvert(value, ty) \
  SWIG_Ruby_CheckConvert(value, ty)
#define SWIG_NewPackedObj(ptr, sz, ty) \
  SWIG_Ruby_NewPackedObj(ptr, sz, ty)
#define SWIG_ConvertPacked(obj, ptr, sz, ty, flags) \
  SWIG_Ruby_ConvertPacked(obj, ptr, sz, ty, flags)

/* rubydef.swg */
#ifdef __cplusplus
extern "C" {
#endif

static VALUE _mSWIG = Qnil;
static VALUE _cSWIG_Pointer = Qnil;
static VALUE swig_runtime_data_type_pointer = Qnil;

/* Initialize Ruby runtime support */
static void
SWIG_Ruby_InitRuntime(void)
{
    VALUE pointer;
    
    if (_mSWIG == Qnil) {
        _mSWIG = rb_define_module("SWIG");
    }
    
    /* first check if pointer already created */
    pointer = rb_gv_get("$swig_runtime_data_type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME);
    if (pointer != Qnil) {
      Data_Get_Struct(pointer, swig_type_info *, swig_type_list_handle);
    } else {
      /* register a new class */
      VALUE cl = rb_define_class("swig_runtime_data", rb_cObject);
      /* create and store the structure pointer to a global variable */
      swig_runtime_data_type_pointer = Data_Wrap_Struct(cl, 0, 0, swig_type_list_handle);
      rb_define_readonly_variable("$swig_runtime_data_type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME, &swig_runtime_data_type_pointer);
    }
}

/* Define Ruby class for C type */
static void
SWIG_Ruby_define_class(swig_type_info *type)
{
    VALUE klass;
    char *klass_name = (char *) malloc(4 + strlen(type->name) + 1);
    sprintf(klass_name, "TYPE%s", type->name);
    if (NIL_P(_cSWIG_Pointer)) {
	_cSWIG_Pointer = rb_define_class_under(_mSWIG, "Pointer", rb_cObject);
	rb_undef_method(CLASS_OF(_cSWIG_Pointer), "new");
    }
    klass = rb_define_class_under(_mSWIG, klass_name, _cSWIG_Pointer);
    free((void *) klass_name);
}

/* Create a new pointer object */
static VALUE
SWIG_Ruby_NewPointerObj(void *ptr, swig_type_info *type, int own)
{
    char *klass_name;
    swig_class *sklass;
    VALUE klass;
    VALUE obj;
    
    if (!ptr)
	return Qnil;
    
    if (type->clientdata) {
      sklass = (swig_class *) type->clientdata;
      obj = Data_Wrap_Struct(sklass->klass, VOIDFUNC(sklass->mark), (own ? VOIDFUNC(sklass->destroy) : 0), ptr);
    } else {
      klass_name = (char *) malloc(4 + strlen(type->name) + 1);
      sprintf(klass_name, "TYPE%s", type->name);
      klass = rb_const_get(_mSWIG, rb_intern(klass_name));
      free((void *) klass_name);
      obj = Data_Wrap_Struct(klass, 0, 0, ptr);
    }
    rb_iv_set(obj, "__swigtype__", rb_str_new2(type->name));
    return obj;
}

/* Create a new class instance (always owned) */
static VALUE
SWIG_Ruby_NewClassInstance(VALUE klass, swig_type_info *type)
{
    VALUE obj;
    swig_class *sklass = (swig_class *) type->clientdata;
    obj = Data_Wrap_Struct(klass, VOIDFUNC(sklass->mark), VOIDFUNC(sklass->destroy), 0);
    rb_iv_set(obj, "__swigtype__", rb_str_new2(type->name));
    return obj;
}

/* Get type mangle from class name */
static SWIGINLINE char *
SWIG_Ruby_MangleStr(VALUE obj)
{
  VALUE stype = rb_iv_get(obj, "__swigtype__");
  return StringValuePtr(stype);
}

/* Convert a pointer value */
static int
SWIG_Ruby_ConvertPtr(VALUE obj, void **ptr, swig_type_info *ty, int flags)
{
  char *c;
  swig_type_info *tc;

  /* Grab the pointer */
  if (NIL_P(obj)) {
    *ptr = 0;
    return 0;
  } else {
    Data_Get_Struct(obj, void, *ptr);
  }
  
  /* Do type-checking if type info was provided */
  if (ty) {
    if (ty->clientdata) {
        if (rb_obj_is_kind_of(obj, ((swig_class *) (ty->clientdata))->klass)) {
          if (*ptr == 0)
            rb_raise(rb_eRuntimeError, "This %s already released", ty->str);
          return 0;
        }
    }
    if ((c = SWIG_MangleStr(obj)) == NULL) {
      if (flags & SWIG_POINTER_EXCEPTION)
        rb_raise(rb_eTypeError, "Expected %s", ty->str);
      else
        return -1;
    }
    tc = SWIG_TypeCheck(c, ty);
    if (!tc) {
      if (flags & SWIG_POINTER_EXCEPTION)
        rb_raise(rb_eTypeError, "Expected %s", ty->str);
      else
        return -1;
    }
    *ptr = SWIG_TypeCast(tc, *ptr);
  }
  return 0;
}

/* Convert a pointer value, signal an exception on a type mismatch */
static SWIGINLINE void *
SWIG_Ruby_MustGetPtr(VALUE obj, swig_type_info *ty, int argnum, int flags)
{
  void *result;
  SWIG_ConvertPtr(obj, &result, ty, flags | SWIG_POINTER_EXCEPTION);
  return result;
}

/* Check convert */
static SWIGINLINE int
SWIG_Ruby_CheckConvert(VALUE obj, swig_type_info *ty)
{
  char *c = SWIG_MangleStr(obj);
  if (!c)
    return 0;
  return SWIG_TypeCheck(c,ty) != 0;
}

static VALUE
SWIG_Ruby_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r, ptr, sz);
  strcpy(r, type->name);
  return rb_str_new2(result);
}

/* Convert a packed value value */
static void
SWIG_Ruby_ConvertPacked(VALUE obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  const char  *c;

  if (TYPE(obj) != T_STRING) goto type_error;
  c = StringValuePtr(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c, ptr, sz);
  if (ty) {
    tc = SWIG_TypeCheck(c, ty);
    if (!tc) goto type_error;
  }
  return;

type_error:

  if (flags) {
    if (ty) {
      rb_raise(rb_eTypeError, "Type error. Expected %s", ty->name);
    } else {
      rb_raise(rb_eTypeError, "Expected a pointer");
    }
  }
}

#ifdef __cplusplus
}
#endif



/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_unsigned_long swig_types[0] 
#define  SWIGTYPE_p_XCC_SESS swig_types[1] 
#define  SWIGTYPE_p_XCC_REQ swig_types[2] 
#define  SWIGTYPE_p_XCC_ITEM swig_types[3] 
#define  SWIGTYPE_p_XCC_CONTENT swig_types[4] 
#define  SWIGTYPE_p_XCC_RES swig_types[5] 
static swig_type_info *swig_types[7];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    Init_Xcc
#define SWIG_name    "Xcc"

static VALUE mXcc;

static void SWIG_AsVal(VALUE obj, int *val)
{
    *val = (int) NUM2INT(obj);
}


#include <marklogic/xcc.h>


VALUE _xccRubyError;
VALUE _xccRubyXQueryError;

static VALUE _xcc_ruby_error_code(VALUE obj) {
    return rb_iv_get(obj, "code");
}

static VALUE _xcc_ruby_error_to_xml(VALUE obj) {
    return rb_iv_get(obj, "error_xml");
}

#define XccError(num, msg) \
     VALUE e = rb_exc_new2(_xccRubyError, msg); \
     rb_iv_set(e, "code", INT2FIX(num)); \
     rb_exc_raise(e);

#define XccErrorXQuery(error_xml) \
     VALUE e = rb_exc_new2(_xccRubyXQueryError, "You have an error in your XQuery"); \
     rb_iv_set(e, "code", INT2FIX(XCC_ERROR_XQUERY)); \
     rb_iv_set(e, "error_xml", rb_tainted_str_new2(error_xml)); \
     rb_exc_raise(e);

static XCC_SESS *new_XCC_SESS(char const *user,char const *password,char const *host,char const *db,int port){
        XCC_SESS *session = xcc_new_session(user, password, host, db, port);
        if(!session) {
            XccError(XCC_ERROR_CONNECTION, "Failed to create new session");
        }

        return session;
    }
static void delete_XCC_SESS(XCC_SESS *self){
        xcc_free_session(self);
    }
static char const *XCC_SESS_server_info(XCC_SESS *self){
        const char *info = xcc_server_info(self);
        if(!info) return "";

        return info;
    }
static XCC_REQ *XCC_SESS_new_adhoc_query(XCC_SESS *self,char const *xquery){
        XCC_REQ *request = xcc_new_adhoc_query(self, xquery);
        if(!request) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return request;
    }
static XCC_REQ *XCC_SESS_new_module_invoke(XCC_SESS *self,char const *module_name){
        XCC_REQ *request = xcc_new_module_invoke(self, module_name);
        if(!request) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return request;
    }
static XCC_REQ *XCC_SESS_new_module_spawn(XCC_SESS *self,char const *module_name){
        XCC_REQ *request = xcc_new_module_spawn(self, module_name);
        if(!request) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return request;
    }
static XCC_CONTENT *XCC_SESS_new_content(XCC_SESS *self){
        XCC_CONTENT *content = xcc_new_content(self);
        if(!content) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return content;
    }
static XCC_RES *XCC_SESS_query(XCC_SESS *self,char const *xquery){
        XCC_RES *result = xcc_query(self, xquery);
        if(!result) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return result;
    }
static XCC_RES *XCC_SESS_invoke(XCC_SESS *self,char const *module){
        XCC_RES *result = xcc_invoke(self, module);
        if(!result) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return result;
    }
static XCC_RES *XCC_SESS_spawn(XCC_SESS *self,char const *module){
        XCC_RES *result = xcc_spawn(self, module);
        if(!result) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return result;
    }

swig_class cSession;
static void free_XCC_SESS(XCC_SESS *);
static XCC_REQ *new_XCC_REQ(){
        XccError(XCC_ERROR_INVALID_ARG, "You can't create new Request objects. You must use methods from Session");
        return NULL;
    }
static void delete_XCC_REQ(XCC_REQ *self){
        xcc_free_request(self);
    }
static XCC_RES *XCC_REQ_submit(XCC_REQ *self){
        XCC_RES *result = xcc_submit_request(self);
        if(!result) {
            if(XCC_ERROR_XQUERY == xcc_req_errcode(self)) {
                XccErrorXQuery(xcc_req_error(self));
            } else {
                XccError(xcc_req_errcode(self), xcc_req_error(self));
            }
        }

        return result;
    }
static void XCC_REQ_set_bufsize(XCC_REQ *self,int size){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_BUFSIZE, size);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_timeout(XCC_REQ *self,int seconds){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_TIMEOUT, seconds);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_dbname(XCC_REQ *self,char const *name){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_DBNAME, name);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_dbid(XCC_REQ *self,char const *id){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_DBID, id);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_timestamp(XCC_REQ *self,char const *stamp){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_TIMESTAMP, stamp);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_name(XCC_REQ *self,char const *name){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_NAME, name);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_variable(XCC_REQ *self,int schema_type,char const *ns,char const *name,char const *value){
        XCC_ERROR_CODE ret = xcc_setvar_generic(self, schema_type, ns, name, value);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }

swig_class cRequest;
static void free_XCC_REQ(XCC_REQ *);
static XCC_RES *new_XCC_RES(){
        XccError(XCC_ERROR_INVALID_ARG, "You can't create new Result objects. You must use call submit");
        return NULL;
    }
static void delete_XCC_RES(XCC_RES *self){
        xcc_free_result(self);
    }
static int XCC_RES_has_next(XCC_RES *self){
        return xcc_has_next(self);
    }
static XCC_ITEM *XCC_RES_next_item(XCC_RES *self){
        return xcc_next_item(self);
    }
static void XCC_RES_each(XCC_RES *self){
        while(XCC_RES_has_next(self)) {
            rb_yield(SWIG_NewPointerObj((void *) XCC_RES_next_item(self), SWIGTYPE_p_XCC_ITEM,1));
        }
    }

swig_class cResult;
static void free_XCC_RES(XCC_RES *);
static XCC_ITEM *new_XCC_ITEM(){
        XccError(XCC_ERROR_INVALID_ARG, "You can't create new Item objects. You must use call Result.next_item()");
        return NULL;
    }
static void delete_XCC_ITEM(XCC_ITEM *self){
        xcc_free_item(self);
    }
static char const *XCC_ITEM_to_string(XCC_ITEM *self){
        return xcc_as_string(self);
    }
static double XCC_ITEM_to_double(XCC_ITEM *self){
        return xcc_as_double(self);
    }
static int XCC_ITEM_to_int(XCC_ITEM *self){
        return xcc_as_int(self);
    }
static XCC_SCHEMA_TYPE XCC_ITEM_type(XCC_ITEM *self){
        return xcc_item_type(self);
    }

swig_class cItem;
static void free_XCC_ITEM(XCC_ITEM *);
static XCC_CONTENT *new_XCC_CONTENT(){
        XccError(XCC_ERROR_INVALID_ARG, "You can't create new Content objects. You must use methods from Sesion");
        return NULL;
    }
static void delete_XCC_CONTENT(XCC_CONTENT *self){
        xcc_free_content(self);
    }
static void XCC_CONTENT_clear_collections(XCC_CONTENT *self){
        xcc_clear_collections(self);
    }
static void XCC_CONTENT_clear_permissions(XCC_CONTENT *self){
        xcc_clear_permissions(self);
    }
static void XCC_CONTENT_add_collection(XCC_CONTENT *self,char const *col){
        XCC_ERROR_CODE ret = xcc_content_addcol(self, col);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_add_permission(XCC_CONTENT *self,int capability,char const *role){
        XCC_ERROR_CODE ret = xcc_content_addperm(self, capability, role);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static xcc_off_t XCC_CONTENT_insert(XCC_CONTENT *self){
        xcc_off_t bytes = xcc_insert_content(self);
        if(!bytes) {
            XccError(xcc_content_errcode(self), xcc_content_error(self));
        }

        return bytes;
    }
static void XCC_CONTENT_set_file_name(XCC_CONTENT *self,char const *fname){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_FILE, fname);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_data(XCC_CONTENT *self,char const *str){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_DATA, str, -1L);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_namespace(XCC_CONTENT *self,char const *ns){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_NS, ns);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_uri(XCC_CONTENT *self,char const *uri){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_URI, uri);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_timeout(XCC_CONTENT *self,int seconds){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_TIMEOUT, seconds);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_format(XCC_CONTENT *self,int fmt){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_FORMAT, fmt);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_repair(XCC_CONTENT *self,int rpr){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_REPAIR, rpr);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_quality(XCC_CONTENT *self,int qlty){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_QUALITY, qlty);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }

swig_class cContent;
static void free_XCC_CONTENT(XCC_CONTENT *);
#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_Session_allocate(VALUE self) {
#else
    static VALUE
    _wrap_Session_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_XCC_SESS);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_Session(int argc, VALUE *argv, VALUE self) {
    char *arg1 = (char *) 0 ;
    char *arg2 = (char *) 0 ;
    char *arg3 = (char *) 0 ;
    char *arg4 = (char *) 0 ;
    int arg5 ;
    XCC_SESS *result;
    
    if ((argc < 5) || (argc > 5))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 5)",argc);
    arg1 = StringValuePtr(argv[0]);
    arg2 = StringValuePtr(argv[1]);
    arg3 = StringValuePtr(argv[2]);
    arg4 = StringValuePtr(argv[3]);
    arg5 = NUM2INT(argv[4]);
    result = (XCC_SESS *)new_XCC_SESS((char const *)arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,arg5);
    DATA_PTR(self) = result;
    return self;
}


static void
free_XCC_SESS(XCC_SESS *arg1) {
    delete_XCC_SESS(arg1);
}
static VALUE
_wrap_Session_server_info(int argc, VALUE *argv, VALUE self) {
    XCC_SESS *arg1 = (XCC_SESS *) 0 ;
    char *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_SESS, 1);
    result = (char *)XCC_SESS_server_info(arg1);
    
    vresult = rb_str_new2(result);
    return vresult;
}


static VALUE
_wrap_Session_new_adhoc_query(int argc, VALUE *argv, VALUE self) {
    XCC_SESS *arg1 = (XCC_SESS *) 0 ;
    char *arg2 = (char *) 0 ;
    XCC_REQ *result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_SESS, 1);
    arg2 = StringValuePtr(argv[0]);
    result = (XCC_REQ *)XCC_SESS_new_adhoc_query(arg1,(char const *)arg2);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_XCC_REQ,1);
    return vresult;
}


static VALUE
_wrap_Session_new_module_invoke(int argc, VALUE *argv, VALUE self) {
    XCC_SESS *arg1 = (XCC_SESS *) 0 ;
    char *arg2 = (char *) 0 ;
    XCC_REQ *result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_SESS, 1);
    arg2 = StringValuePtr(argv[0]);
    result = (XCC_REQ *)XCC_SESS_new_module_invoke(arg1,(char const *)arg2);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_XCC_REQ,1);
    return vresult;
}


static VALUE
_wrap_Session_new_module_spawn(int argc, VALUE *argv, VALUE self) {
    XCC_SESS *arg1 = (XCC_SESS *) 0 ;
    char *arg2 = (char *) 0 ;
    XCC_REQ *result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_SESS, 1);
    arg2 = StringValuePtr(argv[0]);
    result = (XCC_REQ *)XCC_SESS_new_module_spawn(arg1,(char const *)arg2);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_XCC_REQ,1);
    return vresult;
}


static VALUE
_wrap_Session_new_content(int argc, VALUE *argv, VALUE self) {
    XCC_SESS *arg1 = (XCC_SESS *) 0 ;
    XCC_CONTENT *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_SESS, 1);
    result = (XCC_CONTENT *)XCC_SESS_new_content(arg1);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_XCC_CONTENT,1);
    return vresult;
}


static VALUE
_wrap_Session_query(int argc, VALUE *argv, VALUE self) {
    XCC_SESS *arg1 = (XCC_SESS *) 0 ;
    char *arg2 = (char *) 0 ;
    XCC_RES *result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_SESS, 1);
    arg2 = StringValuePtr(argv[0]);
    result = (XCC_RES *)XCC_SESS_query(arg1,(char const *)arg2);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_XCC_RES,1);
    return vresult;
}


static VALUE
_wrap_Session_invoke(int argc, VALUE *argv, VALUE self) {
    XCC_SESS *arg1 = (XCC_SESS *) 0 ;
    char *arg2 = (char *) 0 ;
    XCC_RES *result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_SESS, 1);
    arg2 = StringValuePtr(argv[0]);
    result = (XCC_RES *)XCC_SESS_invoke(arg1,(char const *)arg2);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_XCC_RES,1);
    return vresult;
}


static VALUE
_wrap_Session_spawn(int argc, VALUE *argv, VALUE self) {
    XCC_SESS *arg1 = (XCC_SESS *) 0 ;
    char *arg2 = (char *) 0 ;
    XCC_RES *result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_SESS, 1);
    arg2 = StringValuePtr(argv[0]);
    result = (XCC_RES *)XCC_SESS_spawn(arg1,(char const *)arg2);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_XCC_RES,1);
    return vresult;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_Request_allocate(VALUE self) {
#else
    static VALUE
    _wrap_Request_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_XCC_REQ);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_Request(int argc, VALUE *argv, VALUE self) {
    XCC_REQ *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (XCC_REQ *)new_XCC_REQ();
    DATA_PTR(self) = result;
    return self;
}


static void
free_XCC_REQ(XCC_REQ *arg1) {
    delete_XCC_REQ(arg1);
}
static VALUE
_wrap_Request_submit(int argc, VALUE *argv, VALUE self) {
    XCC_REQ *arg1 = (XCC_REQ *) 0 ;
    XCC_RES *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_REQ, 1);
    result = (XCC_RES *)XCC_REQ_submit(arg1);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_XCC_RES,1);
    return vresult;
}


static VALUE
_wrap_Request_bufsizee___(int argc, VALUE *argv, VALUE self) {
    XCC_REQ *arg1 = (XCC_REQ *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_REQ, 1);
    arg2 = NUM2INT(argv[0]);
    XCC_REQ_set_bufsize(arg1,arg2);
    
    return Qnil;
}


static VALUE
_wrap_Request_timeoute___(int argc, VALUE *argv, VALUE self) {
    XCC_REQ *arg1 = (XCC_REQ *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_REQ, 1);
    arg2 = NUM2INT(argv[0]);
    XCC_REQ_set_timeout(arg1,arg2);
    
    return Qnil;
}


static VALUE
_wrap_Request_dbnamee___(int argc, VALUE *argv, VALUE self) {
    XCC_REQ *arg1 = (XCC_REQ *) 0 ;
    char *arg2 = (char *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_REQ, 1);
    arg2 = StringValuePtr(argv[0]);
    XCC_REQ_set_dbname(arg1,(char const *)arg2);
    
    return Qnil;
}


static VALUE
_wrap_Request_dbide___(int argc, VALUE *argv, VALUE self) {
    XCC_REQ *arg1 = (XCC_REQ *) 0 ;
    char *arg2 = (char *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_REQ, 1);
    arg2 = StringValuePtr(argv[0]);
    XCC_REQ_set_dbid(arg1,(char const *)arg2);
    
    return Qnil;
}


static VALUE
_wrap_Request_timestampe___(int argc, VALUE *argv, VALUE self) {
    XCC_REQ *arg1 = (XCC_REQ *) 0 ;
    char *arg2 = (char *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_REQ, 1);
    arg2 = StringValuePtr(argv[0]);
    XCC_REQ_set_timestamp(arg1,(char const *)arg2);
    
    return Qnil;
}


static VALUE
_wrap_Request_namee___(int argc, VALUE *argv, VALUE self) {
    XCC_REQ *arg1 = (XCC_REQ *) 0 ;
    char *arg2 = (char *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_REQ, 1);
    arg2 = StringValuePtr(argv[0]);
    XCC_REQ_set_name(arg1,(char const *)arg2);
    
    return Qnil;
}


static VALUE
_wrap_Request_set_variable(int argc, VALUE *argv, VALUE self) {
    XCC_REQ *arg1 = (XCC_REQ *) 0 ;
    int arg2 ;
    char *arg3 = (char *) 0 ;
    char *arg4 = (char *) 0 ;
    char *arg5 = (char *) 0 ;
    
    if ((argc < 4) || (argc > 4))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 4)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_REQ, 1);
    arg2 = NUM2INT(argv[0]);
    arg3 = StringValuePtr(argv[1]);
    arg4 = StringValuePtr(argv[2]);
    arg5 = StringValuePtr(argv[3]);
    XCC_REQ_set_variable(arg1,arg2,(char const *)arg3,(char const *)arg4,(char const *)arg5);
    
    return Qnil;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_Result_allocate(VALUE self) {
#else
    static VALUE
    _wrap_Result_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_XCC_RES);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_Result(int argc, VALUE *argv, VALUE self) {
    XCC_RES *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (XCC_RES *)new_XCC_RES();
    DATA_PTR(self) = result;
    return self;
}


static void
free_XCC_RES(XCC_RES *arg1) {
    delete_XCC_RES(arg1);
}
static VALUE
_wrap_Result_has_nextq___(int argc, VALUE *argv, VALUE self) {
    XCC_RES *arg1 = (XCC_RES *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_RES, 1);
    result = (int)XCC_RES_has_next(arg1);
    
    vresult = (result ? Qtrue : Qfalse);
    return vresult;
}


static VALUE
_wrap_Result_next_item(int argc, VALUE *argv, VALUE self) {
    XCC_RES *arg1 = (XCC_RES *) 0 ;
    XCC_ITEM *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_RES, 1);
    result = (XCC_ITEM *)XCC_RES_next_item(arg1);
    
    vresult = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_XCC_ITEM,1);
    return vresult;
}


static VALUE
_wrap_Result_each(int argc, VALUE *argv, VALUE self) {
    XCC_RES *arg1 = (XCC_RES *) 0 ;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_RES, 1);
    XCC_RES_each(arg1);
    
    return Qnil;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_Item_allocate(VALUE self) {
#else
    static VALUE
    _wrap_Item_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_XCC_ITEM);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_Item(int argc, VALUE *argv, VALUE self) {
    XCC_ITEM *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (XCC_ITEM *)new_XCC_ITEM();
    DATA_PTR(self) = result;
    return self;
}


static void
free_XCC_ITEM(XCC_ITEM *arg1) {
    delete_XCC_ITEM(arg1);
}
static VALUE
_wrap_Item_to_s(int argc, VALUE *argv, VALUE self) {
    XCC_ITEM *arg1 = (XCC_ITEM *) 0 ;
    char *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_ITEM, 1);
    result = (char *)XCC_ITEM_to_string(arg1);
    
    vresult = rb_str_new2(result);
    return vresult;
}


static VALUE
_wrap_Item_to_f(int argc, VALUE *argv, VALUE self) {
    XCC_ITEM *arg1 = (XCC_ITEM *) 0 ;
    double result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_ITEM, 1);
    result = (double)XCC_ITEM_to_double(arg1);
    
    vresult = rb_float_new(result);
    return vresult;
}


static VALUE
_wrap_Item_to_i(int argc, VALUE *argv, VALUE self) {
    XCC_ITEM *arg1 = (XCC_ITEM *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_ITEM, 1);
    result = (int)XCC_ITEM_to_int(arg1);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_Item_type(int argc, VALUE *argv, VALUE self) {
    XCC_ITEM *arg1 = (XCC_ITEM *) 0 ;
    XCC_SCHEMA_TYPE result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_ITEM, 1);
    result = XCC_ITEM_type(arg1);
    
    {
        vresult = INT2NUM(result);
    }
    return vresult;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_Content_allocate(VALUE self) {
#else
    static VALUE
    _wrap_Content_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_XCC_CONTENT);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_Content(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (XCC_CONTENT *)new_XCC_CONTENT();
    DATA_PTR(self) = result;
    return self;
}


static void
free_XCC_CONTENT(XCC_CONTENT *arg1) {
    delete_XCC_CONTENT(arg1);
}
static VALUE
_wrap_Content_clear_collections(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    XCC_CONTENT_clear_collections(arg1);
    
    return Qnil;
}


static VALUE
_wrap_Content_clear_permissions(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    XCC_CONTENT_clear_permissions(arg1);
    
    return Qnil;
}


static VALUE
_wrap_Content_add_collection(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    char *arg2 = (char *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    arg2 = StringValuePtr(argv[0]);
    XCC_CONTENT_add_collection(arg1,(char const *)arg2);
    
    return Qnil;
}


static VALUE
_wrap_Content_add_permission(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    int arg2 ;
    char *arg3 = (char *) 0 ;
    
    if ((argc < 2) || (argc > 2))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 2)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    arg2 = NUM2INT(argv[0]);
    arg3 = StringValuePtr(argv[1]);
    XCC_CONTENT_add_permission(arg1,arg2,(char const *)arg3);
    
    return Qnil;
}


static VALUE
_wrap_Content_insert(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    xcc_off_t result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    result = XCC_CONTENT_insert(arg1);
    
    {
        vresult = LL2NUM(result);
    }
    return vresult;
}


static VALUE
_wrap_Content_file_namee___(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    char *arg2 = (char *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    arg2 = StringValuePtr(argv[0]);
    XCC_CONTENT_set_file_name(arg1,(char const *)arg2);
    
    return Qnil;
}


static VALUE
_wrap_Content_datae___(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    char *arg2 = (char *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    arg2 = StringValuePtr(argv[0]);
    XCC_CONTENT_set_data(arg1,(char const *)arg2);
    
    return Qnil;
}


static VALUE
_wrap_Content_namespacee___(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    char *arg2 = (char *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    arg2 = StringValuePtr(argv[0]);
    XCC_CONTENT_set_namespace(arg1,(char const *)arg2);
    
    return Qnil;
}


static VALUE
_wrap_Content_urie___(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    char *arg2 = (char *) 0 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    arg2 = StringValuePtr(argv[0]);
    XCC_CONTENT_set_uri(arg1,(char const *)arg2);
    
    return Qnil;
}


static VALUE
_wrap_Content_timeoute___(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    arg2 = NUM2INT(argv[0]);
    XCC_CONTENT_set_timeout(arg1,arg2);
    
    return Qnil;
}


static VALUE
_wrap_Content_formate___(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    arg2 = NUM2INT(argv[0]);
    XCC_CONTENT_set_format(arg1,arg2);
    
    return Qnil;
}


static VALUE
_wrap_Content_repaire___(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    arg2 = NUM2INT(argv[0]);
    XCC_CONTENT_set_repair(arg1,arg2);
    
    return Qnil;
}


static VALUE
_wrap_Content_qualitye___(int argc, VALUE *argv, VALUE self) {
    XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_XCC_CONTENT, 1);
    arg2 = NUM2INT(argv[0]);
    XCC_CONTENT_set_quality(arg1,arg2);
    
    return Qnil;
}



/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_unsigned_long[] = {{"_p_unsigned_long", 0, "unsigned long *|VALUE *", 0, 0, 0, 0},{"_p_unsigned_long", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_XCC_SESS[] = {{"_p_XCC_SESS", 0, "XCC_SESS *", 0, 0, 0, 0},{"_p_XCC_SESS", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_XCC_REQ[] = {{"_p_XCC_REQ", 0, "XCC_REQ *", 0, 0, 0, 0},{"_p_XCC_REQ", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_XCC_ITEM[] = {{"_p_XCC_ITEM", 0, "XCC_ITEM *", 0, 0, 0, 0},{"_p_XCC_ITEM", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_XCC_CONTENT[] = {{"_p_XCC_CONTENT", 0, "XCC_CONTENT *", 0, 0, 0, 0},{"_p_XCC_CONTENT", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_XCC_RES[] = {{"_p_XCC_RES", 0, "XCC_RES *", 0, 0, 0, 0},{"_p_XCC_RES", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_unsigned_long, 
_swigt__p_XCC_SESS, 
_swigt__p_XCC_REQ, 
_swigt__p_XCC_ITEM, 
_swigt__p_XCC_CONTENT, 
_swigt__p_XCC_RES, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */


#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) Init_Xcc(void) {
    int i;
    
    SWIG_InitRuntime();
    mXcc = rb_define_module("Xcc");
    
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        SWIG_define_class(swig_types[i]);
    }
    
    
    _xccRubyXQueryError = rb_define_class_under(mXcc, "XQueryError", rb_eStandardError); \
    rb_define_method(_xccRubyXQueryError, "code", _xcc_ruby_error_code, 0); \
    rb_define_method(_xccRubyXQueryError, "to_xml", _xcc_ruby_error_to_xml, 0); \
    
    _xccRubyError = rb_define_class_under(mXcc, "Error", rb_eStandardError); \
    rb_define_method(_xccRubyError, "code", _xcc_ruby_error_code, 0); \
    
    rb_define_const(mXcc,"INTEGER", INT2NUM(XCC_TYPE_INTEGER));
    rb_define_const(mXcc,"ANYURI", INT2NUM(XCC_TYPE_ANYURI));
    rb_define_const(mXcc,"BASE64BINARY", INT2NUM(XCC_TYPE_BASE64BINARY));
    rb_define_const(mXcc,"BINARY", INT2NUM(XCC_TYPE_BINARY));
    rb_define_const(mXcc,"BOOLEAN", INT2NUM(XCC_TYPE_BOOLEAN));
    rb_define_const(mXcc,"DATE", INT2NUM(XCC_TYPE_DATE));
    rb_define_const(mXcc,"DATETIME", INT2NUM(XCC_TYPE_DATETIME));
    rb_define_const(mXcc,"DAYTIMEDURATION", INT2NUM(XCC_TYPE_DAYTIMEDURATION));
    rb_define_const(mXcc,"DECIMAL", INT2NUM(XCC_TYPE_DECIMAL));
    rb_define_const(mXcc,"DOUBLE", INT2NUM(XCC_TYPE_DOUBLE));
    rb_define_const(mXcc,"DURATION", INT2NUM(XCC_TYPE_DURATION));
    rb_define_const(mXcc,"FLOAT", INT2NUM(XCC_TYPE_FLOAT));
    rb_define_const(mXcc,"GDAY", INT2NUM(XCC_TYPE_GDAY));
    rb_define_const(mXcc,"GMONTH", INT2NUM(XCC_TYPE_GMONTH));
    rb_define_const(mXcc,"GMONTHDAY", INT2NUM(XCC_TYPE_GMONTHDAY));
    rb_define_const(mXcc,"GYEAR", INT2NUM(XCC_TYPE_GYEAR));
    rb_define_const(mXcc,"GYEARMONTH", INT2NUM(XCC_TYPE_GYEARMONTH));
    rb_define_const(mXcc,"HEXBINARY", INT2NUM(XCC_TYPE_HEXBINARY));
    rb_define_const(mXcc,"NODE", INT2NUM(XCC_TYPE_NODE));
    rb_define_const(mXcc,"QNAME", INT2NUM(XCC_TYPE_QNAME));
    rb_define_const(mXcc,"STRING", INT2NUM(XCC_TYPE_STRING));
    rb_define_const(mXcc,"TEXT", INT2NUM(XCC_TYPE_TEXT));
    rb_define_const(mXcc,"TIME", INT2NUM(XCC_TYPE_TIME));
    rb_define_const(mXcc,"YEARMONTHDURATION", INT2NUM(XCC_TYPE_YEARMONTHDURATION));
    rb_define_const(mXcc,"UNKNOWN", INT2NUM(XCC_TYPE_UNKNOWN));
    rb_define_const(mXcc,"FORMAT_NONE", INT2NUM(XCC_CONTENT_FORMAT_NONE));
    rb_define_const(mXcc,"FORMAT_BINARY", INT2NUM(XCC_CONTENT_FORMAT_BINARY));
    rb_define_const(mXcc,"FORMAT_TEXT", INT2NUM(XCC_CONTENT_FORMAT_TEXT));
    rb_define_const(mXcc,"FORMAT_XML", INT2NUM(XCC_CONTENT_FORMAT_XML));
    rb_define_const(mXcc,"CORRECTION_NONE", INT2NUM(XCC_CONTENT_ERROR_CORRECTION_NONE));
    rb_define_const(mXcc,"CORRECTION_FULL", INT2NUM(XCC_CONTENT_ERROR_CORRECTION_FULL));
    rb_define_const(mXcc,"INSERT", INT2NUM(XCC_PERMISSION_INSERT));
    rb_define_const(mXcc,"UPDATE", INT2NUM(XCC_PERMISSION_UPDATE));
    rb_define_const(mXcc,"READ", INT2NUM(XCC_PERMISSION_READ));
    rb_define_const(mXcc,"EXECUTE", INT2NUM(XCC_PERMISSION_EXECUTE));
    
    cSession.klass = rb_define_class_under(mXcc, "Session", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_XCC_SESS, (void *) &cSession);
    rb_define_alloc_func(cSession.klass, _wrap_Session_allocate);
    rb_define_method(cSession.klass, "initialize", _wrap_new_Session, -1);
    rb_define_method(cSession.klass, "server_info", _wrap_Session_server_info, -1);
    rb_define_method(cSession.klass, "new_adhoc_query", _wrap_Session_new_adhoc_query, -1);
    rb_define_method(cSession.klass, "new_module_invoke", _wrap_Session_new_module_invoke, -1);
    rb_define_method(cSession.klass, "new_module_spawn", _wrap_Session_new_module_spawn, -1);
    rb_define_method(cSession.klass, "new_content", _wrap_Session_new_content, -1);
    rb_define_method(cSession.klass, "query", _wrap_Session_query, -1);
    rb_define_method(cSession.klass, "invoke", _wrap_Session_invoke, -1);
    rb_define_method(cSession.klass, "spawn", _wrap_Session_spawn, -1);
    cSession.mark = 0;
    cSession.destroy = (void (*)(void *)) free_XCC_SESS;
    
    cRequest.klass = rb_define_class_under(mXcc, "Request", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_XCC_REQ, (void *) &cRequest);
    rb_define_alloc_func(cRequest.klass, _wrap_Request_allocate);
    rb_define_method(cRequest.klass, "initialize", _wrap_new_Request, -1);
    rb_define_method(cRequest.klass, "submit", _wrap_Request_submit, -1);
    rb_define_method(cRequest.klass, "bufsize=", _wrap_Request_bufsizee___, -1);
    rb_define_method(cRequest.klass, "timeout=", _wrap_Request_timeoute___, -1);
    rb_define_method(cRequest.klass, "dbname=", _wrap_Request_dbnamee___, -1);
    rb_define_method(cRequest.klass, "dbid=", _wrap_Request_dbide___, -1);
    rb_define_method(cRequest.klass, "timestamp=", _wrap_Request_timestampe___, -1);
    rb_define_method(cRequest.klass, "name=", _wrap_Request_namee___, -1);
    rb_define_method(cRequest.klass, "set_variable", _wrap_Request_set_variable, -1);
    cRequest.mark = 0;
    cRequest.destroy = (void (*)(void *)) free_XCC_REQ;
    
    cResult.klass = rb_define_class_under(mXcc, "Result", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_XCC_RES, (void *) &cResult);
    rb_include_module(cResult.klass, rb_eval_string("Enumerable"));
    rb_define_alloc_func(cResult.klass, _wrap_Result_allocate);
    rb_define_method(cResult.klass, "initialize", _wrap_new_Result, -1);
    rb_define_method(cResult.klass, "has_next?", _wrap_Result_has_nextq___, -1);
    rb_define_method(cResult.klass, "next_item", _wrap_Result_next_item, -1);
    rb_define_method(cResult.klass, "each", _wrap_Result_each, -1);
    cResult.mark = 0;
    cResult.destroy = (void (*)(void *)) free_XCC_RES;
    
    cItem.klass = rb_define_class_under(mXcc, "Item", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_XCC_ITEM, (void *) &cItem);
    rb_define_alloc_func(cItem.klass, _wrap_Item_allocate);
    rb_define_method(cItem.klass, "initialize", _wrap_new_Item, -1);
    rb_define_method(cItem.klass, "to_s", _wrap_Item_to_s, -1);
    rb_define_method(cItem.klass, "to_f", _wrap_Item_to_f, -1);
    rb_define_method(cItem.klass, "to_i", _wrap_Item_to_i, -1);
    rb_define_method(cItem.klass, "type", _wrap_Item_type, -1);
    cItem.mark = 0;
    cItem.destroy = (void (*)(void *)) free_XCC_ITEM;
    
    cContent.klass = rb_define_class_under(mXcc, "Content", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_XCC_CONTENT, (void *) &cContent);
    rb_define_alloc_func(cContent.klass, _wrap_Content_allocate);
    rb_define_method(cContent.klass, "initialize", _wrap_new_Content, -1);
    rb_define_method(cContent.klass, "clear_collections", _wrap_Content_clear_collections, -1);
    rb_define_method(cContent.klass, "clear_permissions", _wrap_Content_clear_permissions, -1);
    rb_define_method(cContent.klass, "add_collection", _wrap_Content_add_collection, -1);
    rb_define_method(cContent.klass, "add_permission", _wrap_Content_add_permission, -1);
    rb_define_method(cContent.klass, "insert", _wrap_Content_insert, -1);
    rb_define_method(cContent.klass, "file_name=", _wrap_Content_file_namee___, -1);
    rb_define_method(cContent.klass, "data=", _wrap_Content_datae___, -1);
    rb_define_method(cContent.klass, "namespace=", _wrap_Content_namespacee___, -1);
    rb_define_method(cContent.klass, "uri=", _wrap_Content_urie___, -1);
    rb_define_method(cContent.klass, "timeout=", _wrap_Content_timeoute___, -1);
    rb_define_method(cContent.klass, "format=", _wrap_Content_formate___, -1);
    rb_define_method(cContent.klass, "repair=", _wrap_Content_repaire___, -1);
    rb_define_method(cContent.klass, "quality=", _wrap_Content_qualitye___, -1);
    cContent.mark = 0;
    cContent.destroy = (void (*)(void *)) free_XCC_CONTENT;
}

