/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#ifndef SWIG_TEMPLATE_DISAMBIGUATOR
#  if defined(__SUNPRO_CC) 
#    define SWIG_TEMPLATE_DISAMBIGUATOR template
#  else
#    define SWIG_TEMPLATE_DISAMBIGUATOR 
#  endif
#endif

/***********************************************************************
 * swigrun.swg
 *
 *     This file contains generic CAPI SWIG runtime support for pointer
 *     type checking.
 *
 ************************************************************************/

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "1"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
#define SWIG_QUOTE_STRING(x) #x
#define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
#define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
#define SWIG_TYPE_TABLE_NAME
#endif

#include <string.h>

#ifndef SWIGINLINE
#if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#  define SWIGINLINE inline
#else
#  define SWIGINLINE
#endif
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the swig runtime code.
  In 99.9% of the cases, swig just needs to declare them as 'static'.
  
  But only do this if is strictly necessary, ie, if you have problems
  with your compiler or so.
*/
#ifndef SWIGRUNTIME
#define SWIGRUNTIME static
#endif
#ifndef SWIGRUNTIMEINLINE
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

/* 
  Compare two type names skipping the space characters, therefore
  "char*" == "char *" and "Class<int>" == "Class<int >", etc.

  Return 0 when the two name types are equivalent, as in
  strncmp, but skipping ' '.
*/
SWIGRUNTIME int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return *f1 - *f2;
  }
  return (l1 - f1) - (l2 - f2);
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
*/
SWIGRUNTIME int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  int equiv = 0;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (!equiv && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te) == 0;
    if (*ne) ++ne;
  }
  return equiv;
}

/*
  Register a type mapping with the type-checking
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeRegisterTL(swig_type_info **tl, swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = *tl;
  while (tc) {
    /* check simple type equivalence */
    int typeequiv = (strcmp(tc->name, ti->name) == 0);   
    /* check full type equivalence, resolving typedefs */
    if (!typeequiv) {
      /* only if tc is not a typedef (no '|' on it) */
      if (tc->str && ti->str && !strstr(tc->str,"|")) {
	typeequiv = SWIG_TypeEquiv(ti->str,tc->str);
      }
    }
    if (typeequiv) {
      /* Already exists in the table.  Just add additional types to the list */
      if (ti->clientdata) tc->clientdata = ti->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = *tl;
  *tl = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;

  return ret;
}

/*
  Check the typename
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeCheck(const char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/*
  Cast a pointer up an inheritance hierarchy
*/
SWIGRUNTIMEINLINE void *
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr);
}

/* 
   Dynamic pointer casting. Down an inheritance hierarchy
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/*
  Return the name associated with this type
*/
SWIGRUNTIMEINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/*
  Return the pretty name associated with this type,
  that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/*
  Search for a swig_type_info structure
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeQueryTL(swig_type_info *tl, const char *name) {
  swig_type_info *ty = tl;
  while (ty) {
    if (ty->str && (SWIG_TypeEquiv(ty->str,name))) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* 
   Set the clientdata field for a type
*/
SWIGRUNTIME void
SWIG_TypeClientDataTL(swig_type_info *tl, swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = tl;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientDataTL(tl,tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* 
   Pack binary data into a string
*/
SWIGRUNTIME char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static char hex[17] = "0123456789abcdef";
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  register unsigned char uu;
  for (; u != eu; ++u) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* 
   Unpack binary data from a string
*/
SWIGRUNTIME const char *
SWIG_UnpackData(const char *c, void *ptr, size_t sz) {
  register unsigned char *u = (unsigned char *) ptr;
  register const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    register int d = *(c++);
    register unsigned char uu = 0;
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    else 
      return (char *) 0;
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    else 
      return (char *) 0;
    *u = uu;
  }
  return c;
}

/*
  This function will propagate the clientdata field of type to any new
  swig_type_info structures that have been added into the list of
  equivalent types.  It is like calling SWIG_TypeClientData(type,
  clientdata) a second time.
*/
SWIGRUNTIME void
SWIG_PropagateClientDataTL(swig_type_info *tl, swig_type_info *type) {
  swig_type_info *equiv = type->next;
  swig_type_info *tc;
  if (!type->clientdata) return;
  while (equiv) {
    if (!equiv->converter) {
      tc = tl;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0) && !tc->clientdata)
          SWIG_TypeClientDataTL(tl,tc, type->clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* 
   Pack 'void *' into a string buffer.
*/
SWIGRUNTIME char *
SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz) {
  char *r = buff;
  if ((2*sizeof(void *) + 2) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,&ptr,sizeof(void *));
  if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
  strcpy(r,name);
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      *ptr = (void *) 0;
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sizeof(void *));
}

SWIGRUNTIME char *
SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz) {
  char *r = buff;
  size_t lname = (name ? strlen(name) : 0);
  if ((2*sz + 2 + lname) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  if (lname) {
    strncpy(r,name,lname+1);
  } else {
    *r = 0;
  }
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      memset(ptr,0,sz);
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sz);
}

#ifdef __cplusplus
}
#endif

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/


#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if !defined(STATIC_LINKED)
#    define SWIGEXPORT(a) __declspec(dllexport) a
#  else
#    define SWIGEXPORT(a) a
#  endif
#else
#  define SWIGEXPORT(a) a
#endif

#ifdef __cplusplus
extern "C" {
#endif


/*************************************************************************/


/* The static type info list */

static swig_type_info *swig_type_list = 0;
static swig_type_info **swig_type_list_handle = &swig_type_list;
  

/* Register a type mapping with the type-checking */
static swig_type_info *
SWIG_TypeRegister(swig_type_info *ti) {
  return SWIG_TypeRegisterTL(swig_type_list_handle, ti);
}

/* Search for a swig_type_info structure */
static swig_type_info *
SWIG_TypeQuery(const char *name) {
  return SWIG_TypeQueryTL(*swig_type_list_handle, name);
}

/* Set the clientdata field for a type */
static void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  SWIG_TypeClientDataTL(*swig_type_list_handle, ti, clientdata);
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
static void
SWIG_PropagateClientData(swig_type_info *type) {
  SWIG_PropagateClientDataTL(*swig_type_list_handle, type);
}

#ifdef __cplusplus
}
#endif

/* ---------------------------------------------------------------------- -*- c -*-
 * perl5.swg
 *
 * Perl5 runtime library
 * $Header: /cvsroot/swig/SWIG/Lib/perl5/perlrun.swg,v 1.20 2004/11/29 23:13:57 wuzzeb Exp $
 * ----------------------------------------------------------------------------- */

#define SWIGPERL
#define SWIGPERL5
#ifdef __cplusplus
/* Needed on some windows machines---since MS plays funny games with the header files under C++ */
#include <math.h>
#include <stdlib.h>
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

/* Get rid of free and malloc defined by perl */
#undef free
#undef malloc

#ifndef pTHX_
#define pTHX_
#endif

#include <string.h>
#ifdef __cplusplus
}
#endif

/* Macro to call an XS function */

#ifdef PERL_OBJECT 
#  define SWIG_CALLXS(_name) _name(cv,pPerl) 
#else 
#  ifndef MULTIPLICITY 
#    define SWIG_CALLXS(_name) _name(cv) 
#  else 
#    define SWIG_CALLXS(_name) _name(PERL_GET_THX, cv) 
#  endif 
#endif 

/* Contract support */

#define SWIG_contract_assert(expr,msg) if (!(expr)) { SWIG_croak(msg); } else

/* Note: SwigMagicFuncHack is a typedef used to get the C++ compiler to just shut up already */

#ifdef PERL_OBJECT
#define MAGIC_PPERL  CPerlObj *pPerl = (CPerlObj *) this;
typedef int (CPerlObj::*SwigMagicFunc)(SV *, MAGIC *);

#ifdef __cplusplus
extern "C" {
#endif
typedef int (CPerlObj::*SwigMagicFuncHack)(SV *, MAGIC *);
#ifdef __cplusplus
}
#endif

#define SWIG_MAGIC(a,b) (SV *a, MAGIC *b)
#define SWIGCLASS_STATIC
#else
#define MAGIC_PPERL
#define SWIGCLASS_STATIC static
#ifndef MULTIPLICITY
#define SWIG_MAGIC(a,b) (SV *a, MAGIC *b)
typedef int (*SwigMagicFunc)(SV *, MAGIC *);

#ifdef __cplusplus
extern "C" {
#endif
typedef int (*SwigMagicFuncHack)(SV *, MAGIC *);
#ifdef __cplusplus
}
#endif


#else
#define SWIG_MAGIC(a,b) (struct interpreter *interp, SV *a, MAGIC *b)
typedef int (*SwigMagicFunc)(struct interpreter *, SV *, MAGIC *);
#ifdef __cplusplus
extern "C" {
#endif
typedef int (*SwigMagicFuncHack)(struct interpreter *, SV *, MAGIC *);
#ifdef __cplusplus
}
#endif

#endif
#endif

#if defined(WIN32) && defined(PERL_OBJECT) && !defined(PerlIO_exportFILE)
#define PerlIO_exportFILE(fh,fl) (FILE*)(fh)
#endif

/* Modifications for newer Perl 5.005 releases */

#if !defined(PERL_REVISION) || ((PERL_REVISION >= 5) && ((PERL_VERSION < 5) || ((PERL_VERSION == 5) && (PERL_SUBVERSION < 50))))
#  ifndef PL_sv_yes
#    define PL_sv_yes sv_yes
#  endif
#  ifndef PL_sv_undef
#    define PL_sv_undef sv_undef
#  endif
#  ifndef PL_na
#    define PL_na na
#  endif
#endif

#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_OWNER 1
#define SWIG_SHADOW 2

/* Common SWIG API */

#ifdef PERL_OBJECT
#  define SWIG_ConvertPtr(obj, pp, type, flags) \
     SWIG_Perl_ConvertPtr(pPerl, obj, pp, type, flags)
#  define SWIG_NewPointerObj(p, type, flags) \
     SWIG_Perl_NewPointerObj(pPerl, p, type, flags)
#  define SWIG_MakePackedObj(sv, p, s, type)	\
     SWIG_Perl_MakePackedObj(pPerl, sv, p, s, type)
#  define SWIG_ConvertPacked(obj, p, s, type, flags) \
     SWIG_Perl_ConvertPacked(pPerl, obj, p, s, type, flags)

#else
#  define SWIG_ConvertPtr(obj, pp, type, flags) \
     SWIG_Perl_ConvertPtr(obj, pp, type, flags)
#  define SWIG_NewPointerObj(p, type, flags) \
     SWIG_Perl_NewPointerObj(p, type, flags)
#  define SWIG_MakePackedObj(sv, p, s, type)	\
     SWIG_Perl_MakePackedObj(sv, p, s, type )
#  define SWIG_ConvertPacked(obj, p, s, type, flags) \
     SWIG_Perl_ConvertPacked(obj, p, s, type, flags)
#endif

/* Perl-specific API */
#ifdef PERL_OBJECT
#  define SWIG_MakePtr(sv, ptr, type, flags) \
     SWIG_Perl_MakePtr(pPerl, sv, ptr, type, flags)
#  define SWIG_SetError(str) \
     SWIG_Perl_SetError(pPerl, str)
#else
#  define SWIG_MakePtr(sv, ptr, type, flags) \
     SWIG_Perl_MakePtr(sv, ptr, type, flags)
#  define SWIG_SetError(str) \
     SWIG_Perl_SetError(str)
#  define SWIG_SetErrorSV(str) \
     SWIG_Perl_SetErrorSV(str)
#endif

#define SWIG_SetErrorf SWIG_Perl_SetErrorf


#ifdef PERL_OBJECT
#  define SWIG_MAYBE_PERL_OBJECT CPerlObj *pPerl,
#else
#  define SWIG_MAYBE_PERL_OBJECT
#endif

static swig_type_info **
SWIG_Perl_GetTypeListHandle() {
  static void *type_pointer = (void *)0;
  SV *pointer;

  /* first check if pointer already created */
  if (!type_pointer) {
    pointer = get_sv("swig_runtime_data::type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME, FALSE);
    if (pointer && SvOK(pointer)) {
      type_pointer = INT2PTR(swig_type_info **, SvIV(pointer));
    }
  }

  return (swig_type_info **) type_pointer;
}

/*
  Search for a swig_type_info structure
 */
SWIGRUNTIMEINLINE swig_type_info *
SWIG_Perl_GetTypeList() {
  swig_type_info **tlh = SWIG_Perl_GetTypeListHandle();
  return tlh ? *tlh : (swig_type_info*)0;
}

#define SWIG_Runtime_GetTypeList SWIG_Perl_GetTypeList 

static swig_type_info *
SWIG_Perl_TypeCheckRV(SWIG_MAYBE_PERL_OBJECT SV *rv, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (sv_derived_from(rv, (char *) s->name)) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Function for getting a pointer value */

static int
SWIG_Perl_ConvertPtr(SWIG_MAYBE_PERL_OBJECT SV *sv, void **ptr, swig_type_info *_t, int flags) {
  swig_type_info *tc;
  void *voidptr = (void *)0;

  /* If magical, apply more magic */
  if (SvGMAGICAL(sv))
    mg_get(sv);

  /* Check to see if this is an object */
  if (sv_isobject(sv)) {
    SV *tsv = (SV*) SvRV(sv);
    IV tmp = 0;
    if ((SvTYPE(tsv) == SVt_PVHV)) {
      MAGIC *mg;
      if (SvMAGICAL(tsv)) {
        mg = mg_find(tsv,'P');
        if (mg) {
          sv = mg->mg_obj;
          if (sv_isobject(sv)) {
            tmp = SvIV((SV*)SvRV(sv));
          }
        }
      } else {
        return -1;
      }
    } else {
      tmp = SvIV((SV*)SvRV(sv));
    }
    voidptr = (void *)tmp;
    if (!_t) {
      *(ptr) = voidptr;
      return 0;
    }
  } else if (! SvOK(sv)) {            /* Check for undef */
    *(ptr) = (void *) 0;
    return 0;
  } else if (SvTYPE(sv) == SVt_RV) {  /* Check for NULL pointer */
    *(ptr) = (void *) 0;
    if (!SvROK(sv))
      return 0;
    else
      return -1;
  } else {                            /* Don't know what it is */
    *(ptr) = (void *) 0;
    return -1;
  }
  if (_t) {
    /* Now see if the types match */
    char *_c = HvNAME(SvSTASH(SvRV(sv)));
    tc = SWIG_TypeCheck(_c,_t);
    if (!tc) {
      *ptr = voidptr;
      return -1;
    }
    *ptr = SWIG_TypeCast(tc,voidptr);
    return 0;
  }
  *ptr = voidptr;
  return 0;
}

static void
SWIG_Perl_MakePtr(SWIG_MAYBE_PERL_OBJECT SV *sv, void *ptr, swig_type_info *t, int flags) {
  if (ptr && (flags & SWIG_SHADOW)) {
    SV *self;
    SV *obj=newSV(0);
    HV *hash=newHV();
    HV *stash;
    sv_setref_pv(obj, (char *) t->name, ptr);
    stash=SvSTASH(SvRV(obj));
    if (flags & SWIG_OWNER) {
      HV *hv;
      GV *gv=*(GV**)hv_fetch(stash, "OWNER", 5, TRUE);
      if (!isGV(gv))
        gv_init(gv, stash, "OWNER", 5, FALSE);
      hv=GvHVn(gv);
      hv_store_ent(hv, obj, newSViv(1), 0);
    }
    sv_magic((SV *)hash, (SV *)obj, 'P', Nullch, 0);
    SvREFCNT_dec(obj);
    self=newRV_noinc((SV *)hash);
    sv_setsv(sv, self);
    SvREFCNT_dec((SV *)self);
    sv_bless(sv, stash);
  }
  else {
    sv_setref_pv(sv, (char *) t->name, ptr);
  }
}

static SWIGINLINE SV *
SWIG_Perl_NewPointerObj(SWIG_MAYBE_PERL_OBJECT void *ptr, swig_type_info *t, int flags) {
  SV *result = sv_newmortal();
  SWIG_MakePtr(result, ptr, t, flags);
  return result;
}

static void
  SWIG_Perl_MakePackedObj(SWIG_MAYBE_PERL_OBJECT SV *sv, void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  sv_setpv(sv, result);
}

/* Convert a packed value value */
static int
SWIG_Perl_ConvertPacked(SWIG_MAYBE_PERL_OBJECT SV *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  const char  *c = 0;

  if ((!obj) || (!SvOK(obj))) return -1;
  c = SvPV(obj, PL_na);
  /* Pointer values must start with leading underscore */
  if (*c != '_') return -1;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) return -1;
  }
  return 0;
}

static SWIGINLINE void
SWIG_Perl_SetError(SWIG_MAYBE_PERL_OBJECT const char *error) {
  if (error) sv_setpv(perl_get_sv("@", TRUE), error);
}

static SWIGINLINE void
SWIG_Perl_SetErrorSV(SWIG_MAYBE_PERL_OBJECT SV *error) {
  if (error) sv_setsv(perl_get_sv("@", TRUE), error);
}

static void
SWIG_Perl_SetErrorf(const char *fmt, ...) {
  va_list args;
  va_start(args, fmt);
  sv_vsetpvfn(perl_get_sv("@", TRUE), fmt, strlen(fmt), &args, Null(SV**), 0, Null(bool*));
  va_end(args);
}

/* Macros for low-level exception handling */
#define SWIG_fail       goto fail
#define SWIG_croak(x)   { SWIG_SetError(x); goto fail; }
#define SWIG_croakSV(x) { SWIG_SetErrorSV(x); goto fail; }
/* most preprocessors do not support vararg macros :-( */
/* #define SWIG_croakf(x...) { SWIG_SetErrorf(x); goto fail; } */


typedef XS(SwigPerlWrapper);
typedef SwigPerlWrapper *SwigPerlWrapperPtr;

/* Structure for command table */
typedef struct {
  const char         *name;
  SwigPerlWrapperPtr  wrapper;
} swig_command_info;

/* Information for constant table */

#define SWIG_INT     1
#define SWIG_FLOAT   2
#define SWIG_STRING  3
#define SWIG_POINTER 4
#define SWIG_BINARY  5

/* Constant information structure */
typedef struct swig_constant_info {
    int              type;
    const char      *name;
    long             lvalue;
    double           dvalue;
    void            *pvalue;
    swig_type_info **ptype;
} swig_constant_info;

#ifdef __cplusplus
}
#endif

/* Structure for variable table */
typedef struct {
  const char   *name;
  SwigMagicFunc   set;
  SwigMagicFunc   get;
  swig_type_info  **type;
} swig_variable_info;

/* Magic variable code */
#ifndef PERL_OBJECT
#define swig_create_magic(s,a,b,c) _swig_create_magic(s,a,b,c)
  #ifndef MULTIPLICITY
     static void _swig_create_magic(SV *sv, char *name, int (*set)(SV *, MAGIC *), int (*get)(SV *,MAGIC *)) {
  #else
     static void _swig_create_magic(SV *sv, char *name, int (*set)(struct interpreter*, SV *, MAGIC *), int (*get)(struct interpreter*, SV *,MAGIC *)) {
  #endif
#else
#  define swig_create_magic(s,a,b,c) _swig_create_magic(pPerl,s,a,b,c)
static void _swig_create_magic(CPerlObj *pPerl, SV *sv, const char *name, int (CPerlObj::*set)(SV *, MAGIC *), int (CPerlObj::*get)(SV *, MAGIC *)) {
#endif
  MAGIC *mg;
  sv_magic(sv,sv,'U',(char *) name,strlen(name));
  mg = mg_find(sv,'U');
  mg->mg_virtual = (MGVTBL *) malloc(sizeof(MGVTBL));
  mg->mg_virtual->svt_get = (SwigMagicFuncHack) get;
  mg->mg_virtual->svt_set = (SwigMagicFuncHack) set;
  mg->mg_virtual->svt_len = 0;
  mg->mg_virtual->svt_clear = 0;
  mg->mg_virtual->svt_free = 0;
}






#ifdef do_open
  #undef do_open
#endif
#ifdef do_close
  #undef do_close
#endif
#ifdef scalar
  #undef scalar
#endif
#ifdef list
  #undef list
#endif
#ifdef apply
  #undef apply
#endif
#ifdef convert
  #undef convert
#endif
#ifdef Error
  #undef Error
#endif
#ifdef form
  #undef form
#endif
#ifdef vform
  #undef vform
#endif
#ifdef LABEL
  #undef LABEL
#endif
#ifdef METHOD
  #undef METHOD
#endif
#ifdef Move
  #undef Move
#endif
#ifdef yylex
  #undef yylex
#endif
#ifdef yyparse
  #undef yyparse
#endif
#ifdef yyerror
  #undef yyerror
#endif
#ifdef invert
  #undef invert
#endif
#ifdef ref
  #undef ref
#endif
#ifdef ENTER
  #undef ENTER
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_XCC_SESS swig_types[0] 
#define  SWIGTYPE_p_XCC_REQ swig_types[1] 
#define  SWIGTYPE_p_XCC_ITEM swig_types[2] 
#define  SWIGTYPE_p_XCC_CONTENT swig_types[3] 
#define  SWIGTYPE_p_XCC_RES swig_types[4] 
static swig_type_info *swig_types[6];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    boot_Xcc

#define SWIG_name   "Xccc::boot_Xcc"
#define SWIG_prefix "Xccc::"

#ifdef __cplusplus
extern "C"
#endif
#ifndef PERL_OBJECT
#ifndef MULTIPLICITY
SWIGEXPORT(void) SWIG_init (CV* cv);
#else
SWIGEXPORT(void) SWIG_init (pTHXo_ CV* cv);
#endif
#else
SWIGEXPORT(void) SWIG_init (CV *cv, CPerlObj *);
#endif


#include <marklogic/xcc.h>


#define XccError(num, msg) \
    croak("Error: %d - %s", num, msg); 

#define XccErrorXQuery(error_xml) \
    croak("%s", error_xml); 

static XCC_SESS *new_XCC_SESS(char const *user,char const *password,char const *host,char const *db,int port){
        XCC_SESS *session = xcc_new_session(user, password, host, db, port);
        if(!session) {
            XccError(XCC_ERROR_CONNECTION, "Failed to create new session");
        }

        return session;
    }
static void delete_XCC_SESS(XCC_SESS *self){
        xcc_free_session(self);
    }
static char const *XCC_SESS_server_info(XCC_SESS *self){
        const char *info = xcc_server_info(self);
        if(!info) return "";

        return info;
    }
static XCC_REQ *XCC_SESS_new_adhoc_query(XCC_SESS *self,char const *xquery){
        XCC_REQ *request = xcc_new_adhoc_query(self, xquery);
        if(!request) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return request;
    }
static XCC_REQ *XCC_SESS_new_module_invoke(XCC_SESS *self,char const *module_name){
        XCC_REQ *request = xcc_new_module_invoke(self, module_name);
        if(!request) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return request;
    }
static XCC_REQ *XCC_SESS_new_module_spawn(XCC_SESS *self,char const *module_name){
        XCC_REQ *request = xcc_new_module_spawn(self, module_name);
        if(!request) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return request;
    }
static XCC_CONTENT *XCC_SESS_new_content(XCC_SESS *self){
        XCC_CONTENT *content = xcc_new_content(self);
        if(!content) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return content;
    }
static XCC_RES *XCC_SESS_query(XCC_SESS *self,char const *xquery){
        XCC_RES *result = xcc_query(self, xquery);
        if(!result) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return result;
    }
static XCC_RES *XCC_SESS_invoke(XCC_SESS *self,char const *module){
        XCC_RES *result = xcc_invoke(self, module);
        if(!result) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return result;
    }
static XCC_RES *XCC_SESS_spawn(XCC_SESS *self,char const *module){
        XCC_RES *result = xcc_spawn(self, module);
        if(!result) {
            XccError(xcc_errcode(self), xcc_error(self));
        }

        return result;
    }
static XCC_REQ *new_XCC_REQ(){
        XccError(XCC_ERROR_INVALID_ARG, "You can't create new Request objects. You must use methods from Session");
        return NULL;
    }
static void delete_XCC_REQ(XCC_REQ *self){
        xcc_free_request(self);
    }
static XCC_RES *XCC_REQ_submit(XCC_REQ *self){
        XCC_RES *result = xcc_submit_request(self);
        if(!result) {
            if(XCC_ERROR_XQUERY == xcc_req_errcode(self)) {
                XccErrorXQuery(xcc_req_error(self));
            } else {
                XccError(xcc_req_errcode(self), xcc_req_error(self));
            }
        }

        return result;
    }
static void XCC_REQ_set_bufsize(XCC_REQ *self,int size){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_BUFSIZE, size);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_timeout(XCC_REQ *self,int seconds){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_TIMEOUT, seconds);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_dbname(XCC_REQ *self,char const *name){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_DBNAME, name);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_dbid(XCC_REQ *self,char const *id){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_DBID, id);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_timestamp(XCC_REQ *self,char const *stamp){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_TIMESTAMP, stamp);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_name(XCC_REQ *self,char const *name){
        XCC_ERROR_CODE ret = xcc_request_setop(self, XCC_REQ_NAME, name);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_REQ_set_variable(XCC_REQ *self,int schema_type,char const *ns,char const *name,char const *value){
        XCC_ERROR_CODE ret = xcc_setvar_generic(self, schema_type, ns, name, value);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static XCC_RES *new_XCC_RES(){
        XccError(XCC_ERROR_INVALID_ARG, "You can't create new Result objects. You must use call submit");
        return NULL;
    }
static void delete_XCC_RES(XCC_RES *self){
        xcc_free_result(self);
    }
static int XCC_RES_has_next(XCC_RES *self){
        return xcc_has_next(self);
    }
static XCC_ITEM *XCC_RES_next_item(XCC_RES *self){
        return xcc_next_item(self);
    }
static XCC_ITEM *new_XCC_ITEM(){
        XccError(XCC_ERROR_INVALID_ARG, "You can't create new Item objects. You must use call Result.next_item()");
        return NULL;
    }
static void delete_XCC_ITEM(XCC_ITEM *self){
        xcc_free_item(self);
    }
static char const *XCC_ITEM_to_string(XCC_ITEM *self){
        return xcc_as_string(self);
    }
static double XCC_ITEM_to_double(XCC_ITEM *self){
        return xcc_as_double(self);
    }
static int XCC_ITEM_to_int(XCC_ITEM *self){
        return xcc_as_int(self);
    }
static XCC_SCHEMA_TYPE XCC_ITEM_type(XCC_ITEM *self){
        return xcc_item_type(self);
    }
static XCC_CONTENT *new_XCC_CONTENT(){
        XccError(XCC_ERROR_INVALID_ARG, "You can't create new Content objects. You must use methods from Sesion");
        return NULL;
    }
static void delete_XCC_CONTENT(XCC_CONTENT *self){
        xcc_free_content(self);
    }
static void XCC_CONTENT_clear_collections(XCC_CONTENT *self){
        xcc_clear_collections(self);
    }
static void XCC_CONTENT_clear_permissions(XCC_CONTENT *self){
        xcc_clear_permissions(self);
    }
static void XCC_CONTENT_add_collection(XCC_CONTENT *self,char const *col){
        XCC_ERROR_CODE ret = xcc_content_addcol(self, col);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_add_permission(XCC_CONTENT *self,int capability,char const *role){
        XCC_ERROR_CODE ret = xcc_content_addperm(self, capability, role);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static xcc_off_t XCC_CONTENT_insert(XCC_CONTENT *self){
        xcc_off_t bytes = xcc_insert_content(self);
        if(!bytes) {
            XccError(xcc_content_errcode(self), xcc_content_error(self));
        }

        return bytes;
    }
static void XCC_CONTENT_set_file_name(XCC_CONTENT *self,char const *fname){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_FILE, fname);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_data(XCC_CONTENT *self,char const *str){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_DATA, str, -1L);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_namespace(XCC_CONTENT *self,char const *ns){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_NS, ns);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_uri(XCC_CONTENT *self,char const *uri){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_URI, uri);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_timeout(XCC_CONTENT *self,int seconds){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_TIMEOUT, seconds);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_format(XCC_CONTENT *self,int fmt){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_FORMAT, fmt);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_repair(XCC_CONTENT *self,int rpr){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_REPAIR, rpr);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
static void XCC_CONTENT_set_quality(XCC_CONTENT *self,int qlty){
        XCC_ERROR_CODE ret = xcc_content_setop(self, XCC_CONTENT_OPT_QUALITY, qlty);
        if(ret != XCC_OK) {
            XccError(ret, xcc_error_message(ret));
        }
    }
#ifdef PERL_OBJECT
#define MAGIC_CLASS _wrap_Xcc_var::
class _wrap_Xcc_var : public CPerlObj {
public:
#else
#define MAGIC_CLASS
#endif
SWIGCLASS_STATIC int swig_magic_readonly(pTHX_ SV *sv, MAGIC *mg) {
    MAGIC_PPERL
    sv = sv; mg = mg;
    croak("Value is read-only.");
    return 0;
}


#ifdef PERL_OBJECT
};
#endif

#ifdef __cplusplus
extern "C" {
#endif
XS(_wrap_new_Session) {
    {
        char *arg1 = (char *) 0 ;
        char *arg2 = (char *) 0 ;
        char *arg3 = (char *) 0 ;
        char *arg4 = (char *) 0 ;
        int arg5 ;
        XCC_SESS *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 5) || (items > 5)) {
            SWIG_croak("Usage: new_Session(user,password,host,db,port);");
        }
        if (!SvOK((SV*) ST(0))) arg1 = 0;
        else arg1 = (char *) SvPV(ST(0), PL_na);
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        if (!SvOK((SV*) ST(2))) arg3 = 0;
        else arg3 = (char *) SvPV(ST(2), PL_na);
        if (!SvOK((SV*) ST(3))) arg4 = 0;
        else arg4 = (char *) SvPV(ST(3), PL_na);
        arg5 = (int) SvIV(ST(4));
        result = (XCC_SESS *)new_XCC_SESS((char const *)arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,arg5);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_SESS, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_delete_Session) {
    {
        XCC_SESS *arg1 = (XCC_SESS *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: delete_Session(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_SESS,0) < 0) {
                SWIG_croak("Type error in argument 1 of delete_Session. Expected _p_XCC_SESS");
            }
        }
        delete_XCC_SESS(arg1);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Session_server_info) {
    {
        XCC_SESS *arg1 = (XCC_SESS *) 0 ;
        char *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Session_server_info(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_SESS,0) < 0) {
                SWIG_croak("Type error in argument 1 of Session_server_info. Expected _p_XCC_SESS");
            }
        }
        result = (char *)XCC_SESS_server_info(arg1);
        
        ST(argvi) = sv_newmortal();
        if (result) {
            sv_setpv((SV*)ST(argvi++), (char *) result);
        } else {
            sv_setsv((SV*)ST(argvi++), &PL_sv_undef);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Session_new_adhoc_query) {
    {
        XCC_SESS *arg1 = (XCC_SESS *) 0 ;
        char *arg2 = (char *) 0 ;
        XCC_REQ *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Session_new_adhoc_query(self,xquery);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_SESS,0) < 0) {
                SWIG_croak("Type error in argument 1 of Session_new_adhoc_query. Expected _p_XCC_SESS");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        result = (XCC_REQ *)XCC_SESS_new_adhoc_query(arg1,(char const *)arg2);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_REQ, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Session_new_module_invoke) {
    {
        XCC_SESS *arg1 = (XCC_SESS *) 0 ;
        char *arg2 = (char *) 0 ;
        XCC_REQ *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Session_new_module_invoke(self,module_name);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_SESS,0) < 0) {
                SWIG_croak("Type error in argument 1 of Session_new_module_invoke. Expected _p_XCC_SESS");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        result = (XCC_REQ *)XCC_SESS_new_module_invoke(arg1,(char const *)arg2);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_REQ, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Session_new_module_spawn) {
    {
        XCC_SESS *arg1 = (XCC_SESS *) 0 ;
        char *arg2 = (char *) 0 ;
        XCC_REQ *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Session_new_module_spawn(self,module_name);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_SESS,0) < 0) {
                SWIG_croak("Type error in argument 1 of Session_new_module_spawn. Expected _p_XCC_SESS");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        result = (XCC_REQ *)XCC_SESS_new_module_spawn(arg1,(char const *)arg2);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_REQ, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Session_new_content) {
    {
        XCC_SESS *arg1 = (XCC_SESS *) 0 ;
        XCC_CONTENT *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Session_new_content(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_SESS,0) < 0) {
                SWIG_croak("Type error in argument 1 of Session_new_content. Expected _p_XCC_SESS");
            }
        }
        result = (XCC_CONTENT *)XCC_SESS_new_content(arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_CONTENT, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Session_query) {
    {
        XCC_SESS *arg1 = (XCC_SESS *) 0 ;
        char *arg2 = (char *) 0 ;
        XCC_RES *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Session_query(self,xquery);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_SESS,0) < 0) {
                SWIG_croak("Type error in argument 1 of Session_query. Expected _p_XCC_SESS");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        result = (XCC_RES *)XCC_SESS_query(arg1,(char const *)arg2);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_RES, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Session_invoke) {
    {
        XCC_SESS *arg1 = (XCC_SESS *) 0 ;
        char *arg2 = (char *) 0 ;
        XCC_RES *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Session_invoke(self,module);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_SESS,0) < 0) {
                SWIG_croak("Type error in argument 1 of Session_invoke. Expected _p_XCC_SESS");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        result = (XCC_RES *)XCC_SESS_invoke(arg1,(char const *)arg2);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_RES, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Session_spawn) {
    {
        XCC_SESS *arg1 = (XCC_SESS *) 0 ;
        char *arg2 = (char *) 0 ;
        XCC_RES *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Session_spawn(self,module);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_SESS,0) < 0) {
                SWIG_croak("Type error in argument 1 of Session_spawn. Expected _p_XCC_SESS");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        result = (XCC_RES *)XCC_SESS_spawn(arg1,(char const *)arg2);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_RES, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_new_Request) {
    {
        XCC_REQ *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 0) || (items > 0)) {
            SWIG_croak("Usage: new_Request();");
        }
        result = (XCC_REQ *)new_XCC_REQ();
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_REQ, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_delete_Request) {
    {
        XCC_REQ *arg1 = (XCC_REQ *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: delete_Request(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_REQ,0) < 0) {
                SWIG_croak("Type error in argument 1 of delete_Request. Expected _p_XCC_REQ");
            }
        }
        delete_XCC_REQ(arg1);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Request_submit) {
    {
        XCC_REQ *arg1 = (XCC_REQ *) 0 ;
        XCC_RES *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Request_submit(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_REQ,0) < 0) {
                SWIG_croak("Type error in argument 1 of Request_submit. Expected _p_XCC_REQ");
            }
        }
        result = (XCC_RES *)XCC_REQ_submit(arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_RES, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Request_set_bufsize) {
    {
        XCC_REQ *arg1 = (XCC_REQ *) 0 ;
        int arg2 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Request_set_bufsize(self,size);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_REQ,0) < 0) {
                SWIG_croak("Type error in argument 1 of Request_set_bufsize. Expected _p_XCC_REQ");
            }
        }
        arg2 = (int) SvIV(ST(1));
        XCC_REQ_set_bufsize(arg1,arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Request_set_timeout) {
    {
        XCC_REQ *arg1 = (XCC_REQ *) 0 ;
        int arg2 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Request_set_timeout(self,seconds);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_REQ,0) < 0) {
                SWIG_croak("Type error in argument 1 of Request_set_timeout. Expected _p_XCC_REQ");
            }
        }
        arg2 = (int) SvIV(ST(1));
        XCC_REQ_set_timeout(arg1,arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Request_set_dbname) {
    {
        XCC_REQ *arg1 = (XCC_REQ *) 0 ;
        char *arg2 = (char *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Request_set_dbname(self,name);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_REQ,0) < 0) {
                SWIG_croak("Type error in argument 1 of Request_set_dbname. Expected _p_XCC_REQ");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        XCC_REQ_set_dbname(arg1,(char const *)arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Request_set_dbid) {
    {
        XCC_REQ *arg1 = (XCC_REQ *) 0 ;
        char *arg2 = (char *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Request_set_dbid(self,id);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_REQ,0) < 0) {
                SWIG_croak("Type error in argument 1 of Request_set_dbid. Expected _p_XCC_REQ");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        XCC_REQ_set_dbid(arg1,(char const *)arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Request_set_timestamp) {
    {
        XCC_REQ *arg1 = (XCC_REQ *) 0 ;
        char *arg2 = (char *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Request_set_timestamp(self,stamp);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_REQ,0) < 0) {
                SWIG_croak("Type error in argument 1 of Request_set_timestamp. Expected _p_XCC_REQ");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        XCC_REQ_set_timestamp(arg1,(char const *)arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Request_set_name) {
    {
        XCC_REQ *arg1 = (XCC_REQ *) 0 ;
        char *arg2 = (char *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Request_set_name(self,name);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_REQ,0) < 0) {
                SWIG_croak("Type error in argument 1 of Request_set_name. Expected _p_XCC_REQ");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        XCC_REQ_set_name(arg1,(char const *)arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Request_set_variable) {
    {
        XCC_REQ *arg1 = (XCC_REQ *) 0 ;
        int arg2 ;
        char *arg3 = (char *) 0 ;
        char *arg4 = (char *) 0 ;
        char *arg5 = (char *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 5) || (items > 5)) {
            SWIG_croak("Usage: Request_set_variable(self,schema_type,ns,name,value);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_REQ,0) < 0) {
                SWIG_croak("Type error in argument 1 of Request_set_variable. Expected _p_XCC_REQ");
            }
        }
        arg2 = (int) SvIV(ST(1));
        if (!SvOK((SV*) ST(2))) arg3 = 0;
        else arg3 = (char *) SvPV(ST(2), PL_na);
        if (!SvOK((SV*) ST(3))) arg4 = 0;
        else arg4 = (char *) SvPV(ST(3), PL_na);
        if (!SvOK((SV*) ST(4))) arg5 = 0;
        else arg5 = (char *) SvPV(ST(4), PL_na);
        XCC_REQ_set_variable(arg1,arg2,(char const *)arg3,(char const *)arg4,(char const *)arg5);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_new_Result) {
    {
        XCC_RES *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 0) || (items > 0)) {
            SWIG_croak("Usage: new_Result();");
        }
        result = (XCC_RES *)new_XCC_RES();
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_RES, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_delete_Result) {
    {
        XCC_RES *arg1 = (XCC_RES *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: delete_Result(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_RES,0) < 0) {
                SWIG_croak("Type error in argument 1 of delete_Result. Expected _p_XCC_RES");
            }
        }
        delete_XCC_RES(arg1);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Result_has_next) {
    {
        XCC_RES *arg1 = (XCC_RES *) 0 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Result_has_next(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_RES,0) < 0) {
                SWIG_croak("Type error in argument 1 of Result_has_next. Expected _p_XCC_RES");
            }
        }
        result = (int)XCC_RES_has_next(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Result_next_item) {
    {
        XCC_RES *arg1 = (XCC_RES *) 0 ;
        XCC_ITEM *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Result_next_item(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_RES,0) < 0) {
                SWIG_croak("Type error in argument 1 of Result_next_item. Expected _p_XCC_RES");
            }
        }
        result = (XCC_ITEM *)XCC_RES_next_item(arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_ITEM, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_new_Item) {
    {
        XCC_ITEM *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 0) || (items > 0)) {
            SWIG_croak("Usage: new_Item();");
        }
        result = (XCC_ITEM *)new_XCC_ITEM();
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_ITEM, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_delete_Item) {
    {
        XCC_ITEM *arg1 = (XCC_ITEM *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: delete_Item(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_ITEM,0) < 0) {
                SWIG_croak("Type error in argument 1 of delete_Item. Expected _p_XCC_ITEM");
            }
        }
        delete_XCC_ITEM(arg1);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Item_to_string) {
    {
        XCC_ITEM *arg1 = (XCC_ITEM *) 0 ;
        char *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Item_to_string(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_ITEM,0) < 0) {
                SWIG_croak("Type error in argument 1 of Item_to_string. Expected _p_XCC_ITEM");
            }
        }
        result = (char *)XCC_ITEM_to_string(arg1);
        
        ST(argvi) = sv_newmortal();
        if (result) {
            sv_setpv((SV*)ST(argvi++), (char *) result);
        } else {
            sv_setsv((SV*)ST(argvi++), &PL_sv_undef);
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Item_to_double) {
    {
        XCC_ITEM *arg1 = (XCC_ITEM *) 0 ;
        double result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Item_to_double(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_ITEM,0) < 0) {
                SWIG_croak("Type error in argument 1 of Item_to_double. Expected _p_XCC_ITEM");
            }
        }
        result = (double)XCC_ITEM_to_double(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setnv(ST(argvi++), (double) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Item_to_int) {
    {
        XCC_ITEM *arg1 = (XCC_ITEM *) 0 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Item_to_int(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_ITEM,0) < 0) {
                SWIG_croak("Type error in argument 1 of Item_to_int. Expected _p_XCC_ITEM");
            }
        }
        result = (int)XCC_ITEM_to_int(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Item_type) {
    {
        XCC_ITEM *arg1 = (XCC_ITEM *) 0 ;
        XCC_SCHEMA_TYPE result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Item_type(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_ITEM,0) < 0) {
                SWIG_croak("Type error in argument 1 of Item_type. Expected _p_XCC_ITEM");
            }
        }
        result = XCC_ITEM_type(arg1);
        
        {
            ST(argvi) = sv_newmortal();
            sv_setiv(ST(argvi), (IV) result);
            argvi++;
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_new_Content) {
    {
        XCC_CONTENT *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 0) || (items > 0)) {
            SWIG_croak("Usage: new_Content();");
        }
        result = (XCC_CONTENT *)new_XCC_CONTENT();
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_XCC_CONTENT, SWIG_SHADOW|SWIG_OWNER);
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_delete_Content) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: delete_Content(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of delete_Content. Expected _p_XCC_CONTENT");
            }
        }
        delete_XCC_CONTENT(arg1);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_clear_collections) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Content_clear_collections(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_clear_collections. Expected _p_XCC_CONTENT");
            }
        }
        XCC_CONTENT_clear_collections(arg1);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_clear_permissions) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Content_clear_permissions(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_clear_permissions. Expected _p_XCC_CONTENT");
            }
        }
        XCC_CONTENT_clear_permissions(arg1);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_add_collection) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        char *arg2 = (char *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Content_add_collection(self,col);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_add_collection. Expected _p_XCC_CONTENT");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        XCC_CONTENT_add_collection(arg1,(char const *)arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_add_permission) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        int arg2 ;
        char *arg3 = (char *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 3) || (items > 3)) {
            SWIG_croak("Usage: Content_add_permission(self,capability,role);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_add_permission. Expected _p_XCC_CONTENT");
            }
        }
        arg2 = (int) SvIV(ST(1));
        if (!SvOK((SV*) ST(2))) arg3 = 0;
        else arg3 = (char *) SvPV(ST(2), PL_na);
        XCC_CONTENT_add_permission(arg1,arg2,(char const *)arg3);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_insert) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        xcc_off_t result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: Content_insert(self);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_insert. Expected _p_XCC_CONTENT");
            }
        }
        result = XCC_CONTENT_insert(arg1);
        
        {
            ST(argvi) = sv_newmortal();
            sv_setuv(ST(argvi), (UV)result);
            argvi++;
        }
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_set_file_name) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        char *arg2 = (char *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Content_set_file_name(self,fname);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_set_file_name. Expected _p_XCC_CONTENT");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        XCC_CONTENT_set_file_name(arg1,(char const *)arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_set_data) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        char *arg2 = (char *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Content_set_data(self,str);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_set_data. Expected _p_XCC_CONTENT");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        XCC_CONTENT_set_data(arg1,(char const *)arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_set_namespace) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        char *arg2 = (char *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Content_set_namespace(self,ns);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_set_namespace. Expected _p_XCC_CONTENT");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        XCC_CONTENT_set_namespace(arg1,(char const *)arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_set_uri) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        char *arg2 = (char *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Content_set_uri(self,uri);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_set_uri. Expected _p_XCC_CONTENT");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        XCC_CONTENT_set_uri(arg1,(char const *)arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_set_timeout) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        int arg2 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Content_set_timeout(self,seconds);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_set_timeout. Expected _p_XCC_CONTENT");
            }
        }
        arg2 = (int) SvIV(ST(1));
        XCC_CONTENT_set_timeout(arg1,arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_set_format) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        int arg2 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Content_set_format(self,fmt);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_set_format. Expected _p_XCC_CONTENT");
            }
        }
        arg2 = (int) SvIV(ST(1));
        XCC_CONTENT_set_format(arg1,arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_set_repair) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        int arg2 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Content_set_repair(self,rpr);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_set_repair. Expected _p_XCC_CONTENT");
            }
        }
        arg2 = (int) SvIV(ST(1));
        XCC_CONTENT_set_repair(arg1,arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}


XS(_wrap_Content_set_quality) {
    {
        XCC_CONTENT *arg1 = (XCC_CONTENT *) 0 ;
        int arg2 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: Content_set_quality(self,qlty);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_XCC_CONTENT,0) < 0) {
                SWIG_croak("Type error in argument 1 of Content_set_quality. Expected _p_XCC_CONTENT");
            }
        }
        arg2 = (int) SvIV(ST(1));
        XCC_CONTENT_set_quality(arg1,arg2);
        
        
        XSRETURN(argvi);
        fail:
        ;
    }
    croak(Nullch);
}



/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_XCC_SESS[] = {{"Xcc::Session", 0, "XCC_SESS *", 0, 0, 0, 0},{"Xcc::Session", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_XCC_REQ[] = {{"Xcc::Request", 0, "XCC_REQ *", 0, 0, 0, 0},{"Xcc::Request", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_XCC_ITEM[] = {{"Xcc::Item", 0, "XCC_ITEM *", 0, 0, 0, 0},{"Xcc::Item", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_XCC_CONTENT[] = {{"Xcc::Content", 0, "XCC_CONTENT *", 0, 0, 0, 0},{"Xcc::Content", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_XCC_RES[] = {{"Xcc::Result", 0, "XCC_RES *", 0, 0, 0, 0},{"Xcc::Result", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_XCC_SESS, 
_swigt__p_XCC_REQ, 
_swigt__p_XCC_ITEM, 
_swigt__p_XCC_CONTENT, 
_swigt__p_XCC_RES, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_constant_info swig_constants[] = {
{ SWIG_INT,     (char *) SWIG_prefix "INTEGER", (long) XCC_TYPE_INTEGER, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "ANYURI", (long) XCC_TYPE_ANYURI, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "BASE64BINARY", (long) XCC_TYPE_BASE64BINARY, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "BINARY", (long) XCC_TYPE_BINARY, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "BOOLEAN", (long) XCC_TYPE_BOOLEAN, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "DATE", (long) XCC_TYPE_DATE, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "DATETIME", (long) XCC_TYPE_DATETIME, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "DAYTIMEDURATION", (long) XCC_TYPE_DAYTIMEDURATION, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "DECIMAL", (long) XCC_TYPE_DECIMAL, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "DOUBLE", (long) XCC_TYPE_DOUBLE, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "DURATION", (long) XCC_TYPE_DURATION, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "FLOAT", (long) XCC_TYPE_FLOAT, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "GDAY", (long) XCC_TYPE_GDAY, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "GMONTH", (long) XCC_TYPE_GMONTH, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "GMONTHDAY", (long) XCC_TYPE_GMONTHDAY, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "GYEAR", (long) XCC_TYPE_GYEAR, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "GYEARMONTH", (long) XCC_TYPE_GYEARMONTH, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "HEXBINARY", (long) XCC_TYPE_HEXBINARY, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "NODE", (long) XCC_TYPE_NODE, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "QNAME", (long) XCC_TYPE_QNAME, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "STRING", (long) XCC_TYPE_STRING, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "TEXT", (long) XCC_TYPE_TEXT, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "TIME", (long) XCC_TYPE_TIME, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "YEARMONTHDURATION", (long) XCC_TYPE_YEARMONTHDURATION, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "UNKNOWN", (long) XCC_TYPE_UNKNOWN, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "FORMAT_NONE", (long) XCC_CONTENT_FORMAT_NONE, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "FORMAT_BINARY", (long) XCC_CONTENT_FORMAT_BINARY, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "FORMAT_TEXT", (long) XCC_CONTENT_FORMAT_TEXT, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "FORMAT_XML", (long) XCC_CONTENT_FORMAT_XML, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "CORRECTION_NONE", (long) XCC_CONTENT_ERROR_CORRECTION_NONE, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "CORRECTION_FULL", (long) XCC_CONTENT_ERROR_CORRECTION_FULL, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "INSERT", (long) XCC_PERMISSION_INSERT, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "UPDATE", (long) XCC_PERMISSION_UPDATE, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "READ", (long) XCC_PERMISSION_READ, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "EXECUTE", (long) XCC_PERMISSION_EXECUTE, 0, 0, 0},
{0,0,0,0,0,0}
};
#ifdef __cplusplus
}
#endif
static swig_variable_info swig_variables[] = {
{0,0,0,0}
};
static swig_command_info swig_commands[] = {
{"Xccc::new_Session", _wrap_new_Session},
{"Xccc::delete_Session", _wrap_delete_Session},
{"Xccc::Session_server_info", _wrap_Session_server_info},
{"Xccc::Session_new_adhoc_query", _wrap_Session_new_adhoc_query},
{"Xccc::Session_new_module_invoke", _wrap_Session_new_module_invoke},
{"Xccc::Session_new_module_spawn", _wrap_Session_new_module_spawn},
{"Xccc::Session_new_content", _wrap_Session_new_content},
{"Xccc::Session_query", _wrap_Session_query},
{"Xccc::Session_invoke", _wrap_Session_invoke},
{"Xccc::Session_spawn", _wrap_Session_spawn},
{"Xccc::new_Request", _wrap_new_Request},
{"Xccc::delete_Request", _wrap_delete_Request},
{"Xccc::Request_submit", _wrap_Request_submit},
{"Xccc::Request_set_bufsize", _wrap_Request_set_bufsize},
{"Xccc::Request_set_timeout", _wrap_Request_set_timeout},
{"Xccc::Request_set_dbname", _wrap_Request_set_dbname},
{"Xccc::Request_set_dbid", _wrap_Request_set_dbid},
{"Xccc::Request_set_timestamp", _wrap_Request_set_timestamp},
{"Xccc::Request_set_name", _wrap_Request_set_name},
{"Xccc::Request_set_variable", _wrap_Request_set_variable},
{"Xccc::new_Result", _wrap_new_Result},
{"Xccc::delete_Result", _wrap_delete_Result},
{"Xccc::Result_has_next", _wrap_Result_has_next},
{"Xccc::Result_next_item", _wrap_Result_next_item},
{"Xccc::new_Item", _wrap_new_Item},
{"Xccc::delete_Item", _wrap_delete_Item},
{"Xccc::Item_to_string", _wrap_Item_to_string},
{"Xccc::Item_to_double", _wrap_Item_to_double},
{"Xccc::Item_to_int", _wrap_Item_to_int},
{"Xccc::Item_type", _wrap_Item_type},
{"Xccc::new_Content", _wrap_new_Content},
{"Xccc::delete_Content", _wrap_delete_Content},
{"Xccc::Content_clear_collections", _wrap_Content_clear_collections},
{"Xccc::Content_clear_permissions", _wrap_Content_clear_permissions},
{"Xccc::Content_add_collection", _wrap_Content_add_collection},
{"Xccc::Content_add_permission", _wrap_Content_add_permission},
{"Xccc::Content_insert", _wrap_Content_insert},
{"Xccc::Content_set_file_name", _wrap_Content_set_file_name},
{"Xccc::Content_set_data", _wrap_Content_set_data},
{"Xccc::Content_set_namespace", _wrap_Content_set_namespace},
{"Xccc::Content_set_uri", _wrap_Content_set_uri},
{"Xccc::Content_set_timeout", _wrap_Content_set_timeout},
{"Xccc::Content_set_format", _wrap_Content_set_format},
{"Xccc::Content_set_repair", _wrap_Content_set_repair},
{"Xccc::Content_set_quality", _wrap_Content_set_quality},
{0,0}
};


static void SWIG_Perl_SetTypeListHandle(swig_type_info **handle) {
    SV *pointer;
    
    /* create a new pointer */
    pointer = get_sv("swig_runtime_data::type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME, TRUE);
    sv_setiv(pointer, PTR2IV(swig_type_list_handle));
}

static swig_type_info **
SWIG_Perl_LookupTypePointer(swig_type_info **type_list_handle) {
    swig_type_info **type_pointer;
    
    /* first check if module already created */
    type_pointer = SWIG_Perl_GetTypeListHandle();
    if (type_pointer) {
        return type_pointer;
    } else {
        /* create a new module and variable */
        SWIG_Perl_SetTypeListHandle(type_list_handle);
        return type_list_handle;
    }
}


#ifdef __cplusplus
extern "C"
#endif

XS(SWIG_init) {
    dXSARGS;
    int i;
    static int _init = 0;
    if (!_init) {
        swig_type_list_handle = SWIG_Perl_LookupTypePointer(swig_type_list_handle);
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }	
        _init = 1;
    }
    
    /* Install commands */
    for (i = 0; swig_commands[i].name; i++) {
        newXS((char*) swig_commands[i].name,swig_commands[i].wrapper, (char*)__FILE__);
    }
    
    /* Install variables */
    for (i = 0; swig_variables[i].name; i++) {
        SV *sv;
        sv = perl_get_sv((char*) swig_variables[i].name, TRUE | 0x2);
        if (swig_variables[i].type) {
            SWIG_MakePtr(sv,(void *)1, *swig_variables[i].type,0);
        } else {
            sv_setiv(sv,(IV) 0);
        }
        swig_create_magic(sv, (char *) swig_variables[i].name, swig_variables[i].set, swig_variables[i].get); 
    }
    
    /* Install constant */
    for (i = 0; swig_constants[i].type; i++) {
        SV *sv;
        sv = perl_get_sv((char*)swig_constants[i].name, TRUE | 0x2);
        switch(swig_constants[i].type) {
            case SWIG_INT:
            sv_setiv(sv, (IV) swig_constants[i].lvalue);
            break;
            case SWIG_FLOAT:
            sv_setnv(sv, (double) swig_constants[i].dvalue);
            break;
            case SWIG_STRING:
            sv_setpv(sv, (char *) swig_constants[i].pvalue);
            break;
            case SWIG_POINTER:
            SWIG_MakePtr(sv, swig_constants[i].pvalue, *(swig_constants[i].ptype),0);
            break;
            case SWIG_BINARY:
            SWIG_MakePackedObj(sv, swig_constants[i].pvalue, swig_constants[i].lvalue, *(swig_constants[i].ptype));
            break;
            default:
            break;
        }
        SvREADONLY_on(sv);
    }
    
    SWIG_TypeClientData(SWIGTYPE_p_XCC_SESS, (void*) "Xcc::Session");
    SWIG_TypeClientData(SWIGTYPE_p_XCC_REQ, (void*) "Xcc::Request");
    SWIG_TypeClientData(SWIGTYPE_p_XCC_RES, (void*) "Xcc::Result");
    SWIG_TypeClientData(SWIGTYPE_p_XCC_ITEM, (void*) "Xcc::Item");
    SWIG_TypeClientData(SWIGTYPE_p_XCC_CONTENT, (void*) "Xcc::Content");
    ST(0) = &PL_sv_yes;
    XSRETURN(1);
}

